alibaba/spring-ai-alibaba

README-zh.md, README.md
=> docs: update groupId

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatOptions.java
=> fix: non-streaming error while incremental_output is true

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/DashScopeImageApi.java
=> fix: wanx-v1 not support synchronize

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/DashScopeApi.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatModel.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatOptions.java
=> fix: incremental output error

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/autoconfigure/dashscope/DashScopeAutoConfiguration.java
=> feat: support read apikey from system env

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/common/DashScopeApiConstants.java
- Update apikey constants name
=> feat: update apikey constants name

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/advisor/RetrievalRerankAdvisor.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/autoconfigure/dashscope/DashScopeAutoConfiguration.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/autoconfigure/dashscope/DashScopeRerankProperties.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/DashScopeApi.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/rag/DashScopeDocumentCloudReader.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/rerank/DashScopeRerankModel.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/rerank/DashScopeRerankOptions.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/document/DocumentWithScore.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/model/RerankModel.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/model/RerankOptions.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/model/RerankResponse.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/DashscopeAiTestConfiguration.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/chat/client/DashScopeChatClientIT.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/rerank/DashScopeRerankModelTest.java
1. add rerank model.
2. add retrieval and rerank advisor for rag.
=> feat: rerank model and advisor

spring-ai-alibaba-examples/playground-flight-booking/src/main/java/ai/spring/demo/ai/playground/services/LoggingAdvisor.java
Due to changes in the path of AdvisedRequest in spring ai core, the code in the example needs to be modified
no
=> fix AdvisedRequest import path

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/advisor/DocumentRetrievalAdvisor.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/advisor/RetrievalRerankAdvisor.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/ApiUtils.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/common/DashScopeApiConstants.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/rag/DashScopeDocumentRetrievalAdvisor.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/chat/client/DashScopeChatClientIT.java
1. Update dashscope api user agent.
2. Fix metadata of ChatResponse loss issue in advisor.
Verified with test cases.
=> feat:add user agent

README-zh.md, README.md
Describe what this PR does / why we need it
update the README content to fix someone can't pull the resources from remote repository
Does this pull request fix one issue?
Fixes https://github.com/alibaba/spring-ai-alibaba/issues/66
Describe how you did it
show the local mirror configuration method (maven settings.xml)
=> feat: improve the README content

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/ApiUtils.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/common/DashScopeApiConstants.java
Fix cloud rag issue.
Fix issue for cloud rag import document error.
Verified with test cases.
=> fix: cloud rag issue

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/ApiUtils.java
=> update user agent

pom.xml, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/api/PromptsAPI.java, spring-ai-alibaba-studio/ui/.npmrc, spring-ai-alibaba-studio/ui/package-lock.json, spring-ai-alibaba-studio/ui/package.json, spring-ai-alibaba-studio/ui/src/i18n/locales/en-us.json, spring-ai-alibaba-studio/ui/src/i18n/locales/zh-cn.json, spring-ai-alibaba-studio/ui/src/mock/tracemock.ts, spring-ai-alibaba-studio/ui/src/pages/history/index.tsx, spring-ai-alibaba-studio/ui/src/pages/layout.tsx, spring-ai-alibaba-studio/ui/src/utils/locationUtil.ts
add the traceFont page and fix some ui problem
=> Workflow dev

community/plugins/bing-search-plugin-starter/src/main/java/com/alibaba/cloud/ai/plugin/BingSearchPluginConfiguration.java, community/plugins/bing-search-plugin-starter/src/main/java/com/alibaba/cloud/ai/plugin/BingSearchProperties.java, community/plugins/bing-search-plugin-starter/src/main/java/com/alibaba/cloud/ai/plugin/BingSearchService.java, community/plugins/bing-search-plugin-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
=> bing plugin

community/plugins/bing-search-plugin-starter/pom.xml
=> add pom.xml

community/plugins/baidu-search-plugin-starter/src/main/java/com/alibaba/cloud/plugin/BaiduSearchService.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/DashScopeSpeechSynthesisApi.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/image/DashScopeImageModel.java
This PR introduces key improvements to the code for better readability, maintainability, and functionality. It adds contextual variable names to replace hardcoded numbers, refactors conditional statements for clarity, and improves the naming conventions for variables to make their purpose explicit. These changes enhance the code’s usability and reduce potential confusion for future developers.
NONE
1. Adding Contextual Variables:
a. Replaced hardcoded numbers with variables to improve code readability and reusability.
b. Added Memory_Size to represent the 5MB memory limit.
c. Introduced Memory_Unit with a value of 1024 and Max_Memory_In_MB to convert memory into MB, ensuring the conversion is done outside of function calls for better clarity.
2. Refactoring Conditional Statements:
a. …
=> Refactoring code for better quality

spring-ai-alibaba-examples/ollama-example/README.md, spring-ai-alibaba-examples/ollama-example/pom.xml, spring-ai-alibaba-examples/ollama-example/src/main/java/com/alibaba/cloud/ai/example/ollama/OllamaController.java, spring-ai-alibaba-examples/ollama-example/src/main/java/com/alibaba/cloud/ai/example/ollama/OllamaExampleApplication.java, spring-ai-alibaba-examples/ollama-example/src/main/resources/application.yml
=> add ollama example

community/plugins/spring-ai-alibaba-starter-plugin-baidusearch/src/main/java/com/alibaba/cloud/ai/plugin/baidu/BaiduSearchPluginConfiguration.java, community/plugins/spring-ai-alibaba-starter-plugin-baidusearch/src/main/java/com/alibaba/cloud/ai/plugin/baidu/BaiduSearchService.java, community/plugins/spring-ai-alibaba-starter-plugin-baidusearch/src/test/java/com/alibaba/cloud/ai/plugin/baidu/BaiduSearchServiceTest.java, community/plugins/spring-ai-alibaba-starter-plugin-bingsearch/src/main/java/com/alibaba/cloud/ai/plugin/bing/BingSearchPluginConfiguration.java, community/plugins/spring-ai-alibaba-starter-plugin-bingsearch/src/main/java/com/alibaba/cloud/ai/plugin/bing/BingSearchProperties.java, community/plugins/spring-ai-alibaba-starter-plugin-bingsearch/src/main/java/com/alibaba/cloud/ai/plugin/bing/BingSearchService.java, community/plugins/spring-ai-alibaba-starter-plugin-bingsearch/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, spring-ai-alibaba-examples/function-calling-example/pom.xml, spring-ai-alibaba-examples/function-calling-example/src/main/java/com/alibaba/cloud/ai/example/functioncalling/FunctionCallingController.java, spring-ai-alibaba-examples/function-calling-example/src/main/resources/application.yml
=> Change bing search plugin to meet plugin specification.

community/plugins/spring-ai-alibaba-starter-plugin-weather/pom.xml, community/plugins/spring-ai-alibaba-starter-plugin-weather/src/main/java/com/alibaba/cloud/ai/plugin/weather/WeatherAutoConfiguration.java, community/plugins/spring-ai-alibaba-starter-plugin-weather/src/main/java/com/alibaba/cloud/ai/plugin/weather/WeatherProperties.java, community/plugins/spring-ai-alibaba-starter-plugin-weather/src/main/java/com/alibaba/cloud/ai/plugin/weather/WeatherService.java, community/plugins/spring-ai-alibaba-starter-plugin-weather/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, pom.xml, spring-ai-alibaba-examples/function-calling-example/pom.xml, spring-ai-alibaba-examples/function-calling-example/src/main/java/com/alibaba/cloud/ai/example/functioncalling/FunctionCallingController.java, spring-ai-alibaba-examples/function-calling-example/src/main/resources/application.yml
add a plugin to get the weather function
It is used to obtain the current weather and forecast weather information of the corresponding city
#98
=> Feat: Intergration Weather PluginTool

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/pom.xml, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/CompileConfig.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/RunnableConfig.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/checkpoint/BaseCheckpointSaver.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/checkpoint/Checkpoint.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/checkpoint/config/SaverConfig.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/checkpoint/constant/SaverConstant.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/checkpoint/savers/FileSystemSaver.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/checkpoint/savers/MemorySaver.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/checkpoint/savers/MongoSaver.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/checkpoint/savers/RedisSaver.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/serializer/check_point/CheckPointSerializer.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/CheckPointConfigTest.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/StateGraphMongoPersistenceTest.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/StateGraphPersistenceTest.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/StateGraphRedisPersistenceTest.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/org/bsc/langgraph4j/studio/LangGraphStreamingServer.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/org/bsc/langgraph4j/studio/jetty/LangGraphStreamingServerJetty.java
add redis saver
add redis saver
None
implement BaseCheckpointSaver by redisson
run com.alibaba.cloud.ai.graph.StateGraphRedisPersistenceTest
=> :busts_in_silhouette: Checkpoint

spring-ai-alibaba-autoconfigure/src/main/java/com/alibaba/cloud/ai/autoconfigure/dashscope/DashScopeAutoConfiguration.java, spring-ai-alibaba-examples/observability-example/compose.yaml, spring-ai-alibaba-examples/observability-example/src/main/java/com/alibaba/cloud/ai/example/observability/ObservabilityApplication.java, spring-ai-alibaba-examples/observability-example/src/main/resources/application.properties
=> Auto configure observation registry of DashScope ChatModel & make trace id accessible in observability example.

spring-ai-alibaba-examples/cli-debug-example/src/main/resources/application.yml, spring-ai-alibaba-studio/pom.xml, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/api/ChatModelAPI.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/config/ObserverConfiguration.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/config/WebConfig.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/tracing/TraceIdInterceptor.java, spring-ai-alibaba-studio/src/main/resources/openapi.yaml, spring-ai-alibaba-studio/ui/src/pages/run/models/ChatModel/index.tsx, spring-ai-alibaba-studio/ui/src/pages/run/models/ImageModel/index.tsx, spring-ai-alibaba-studio/ui/src/pages/run/models/Setup/Config/index.tsx, spring-ai-alibaba-studio/ui/src/pages/run/models/Setup/Tool/index.tsx, spring-ai-alibaba-studio/ui/src/pages/run/models/Setup/index.tsx, spring-ai-alibaba-studio/ui/src/pages/run/models/types.ts, spring-ai-alibaba-studio/ui/src/services/chat_models.ts, spring-ai-alibaba-studio/ui/src/types/options.ts
=> studio: add trace, rightpanel and show img

spring-ai-alibaba-examples/zhipuai-example/pom.xml, spring-ai-alibaba-examples/zhipuai-example/src/main/java/com/alibaba/cloud/ai/example/zhipuai/ZhiPuAiController.java, spring-ai-alibaba-examples/zhipuai-example/src/main/java/com/alibaba/cloud/ai/example/zhipuai/ZhiPuAiExampleApplication.java, spring-ai-alibaba-examples/zhipuai-example/src/main/resources/application.yml
1. add zhipuai model examples，The only free online large model API provider.
#56 
run example
=> 1.add zhipuai model example

pom.xml, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/DashScopeApi.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/DashScopeResponseFormat.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatModel.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatOptions.java, spring-ai-alibaba-examples/chatmodel-example/pom.xml, spring-ai-alibaba-examples/chatmodel-example/src/main/java/com/alibaba/cloud/ai/example/model/ChatModelController.java, spring-ai-alibaba-examples/chatmodel-example/src/main/resources/application.yml
- Add `response_types` request params
=> feat: add response_format params

community/plugins/spring-ai-alibaba-starter-plugin-serpapi/pom.xml, community/plugins/spring-ai-alibaba-starter-plugin-serpapi/src/main/java/com/alibaba/cloud/ai/plugin/serpapi/SerpApiConfiguration.java, community/plugins/spring-ai-alibaba-starter-plugin-serpapi/src/main/java/com/alibaba/cloud/ai/plugin/serpapi/SerpApiProperties.java, community/plugins/spring-ai-alibaba-starter-plugin-serpapi/src/main/java/com/alibaba/cloud/ai/plugin/serpapi/SerpApiService.java, community/plugins/spring-ai-alibaba-starter-plugin-serpapi/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
=> Add SerpApi search plugin

spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/locales/zh-CN.ts, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/pages/Graph/Design/index.tsx, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/pages/Graph/Design/map.tsx, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/pages/Graph/index.tsx
Use i18n key to replace the original text in Chinese.
NONE
If the text in Chinese display correctly then it works.
=> chore(front-end): Update text to use i18n key

CONTRIBUTING.md, README-zh.md, README.md
This PR adds a contribution guidelines document to help new contributors understand the process and standards for contributing to the project. It aims to streamline collaboration and ensure consistency in contributions.
NONE
I created a new document outlining the steps and best practices for contributing to the project. This includes sections on code style, submission process, and review guidelines.
Review the contribution guidelines document to ensure it covers all necessary aspects of the contribution process and aligns with the project's standards.
Please check if there are any additional sections or details that should be included in the contribution guidelines to make it more comprehensive.
=> Doc : Added contribution guidelines document

community/function-calling/spring-ai-alibaba-starter-function-calling-translate/pom.xml, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/DashScopeAiStreamFunctionCallingHelper.java
1. support function calling stream output
Fixes: #199
#215 
```java
String name = (current.name() != null && !current.name().isEmpty() ? current.name() : previous.name());
```
=> [hotfix]: fix stream function calling exception

community/function-calling/spring-ai-alibaba-starter-function-calling-amap/src/main/java/com/alibaba/cloud/ai/functioncalling/amp/AmapProperties.java, community/function-calling/spring-ai-alibaba-starter-function-calling-amap/src/main/java/com/alibaba/cloud/ai/functioncalling/amp/WeatherSearchService.java, community/function-calling/spring-ai-alibaba-starter-function-calling-jsonprocessor/src/main/java/com/alibaba/cloud/ai/functioncalling/jsonprocessor/JsonAutoConfiguration.java, community/function-calling/spring-ai-alibaba-starter-function-calling-serpapi/src/main/java/com/alibaba/cloud/ai/functioncalling/serpapi/SerpApiAutoConfiguration.java, community/function-calling/spring-ai-alibaba-starter-function-calling-translate/src/main/java/com/alibaba/cloud/ai/functioncalling/translate/TranslateAutoConfiguration.java, community/function-calling/spring-ai-alibaba-starter-function-calling-weather/src/main/java/com/alibaba/cloud/ai/functioncalling/weather/WeatherProperties.java, spring-ai-alibaba-autoconfigure/src/main/java/com/alibaba/cloud/ai/autoconfigure/dashscope/DashScopeAutoConfiguration.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatModel.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/common/DashScopeApiConstants.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/embedding/DashScopeEmbeddingModel.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/observation/conventions/AiProvider.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatModelObservationIT.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/embedding/DashScopeEmbeddingModelObservationIT.java
to #225 
P.S. The latest commit is just adjusting the code format so you can ignore it. ;)
=> feat: add DashScopeEmbeddingModel observability

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/checkpoint/savers/RedisSaver.java
原代码当未获得锁时，finally都做了unlock操作，这样会存在问题
unlock操作时，增加是否获得锁判断
=> Fix the unlock issue of RedisSaver.

spring-ai-alibaba-studio/.gitignore, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/api/ChatModelAPI.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/common/R.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/service/ChatModelDelegate.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/service/impl/ChatModelDelegateImpl.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/tracing/GlobalResponseBodyAdvice.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/tracing/TraceIdInterceptor.java, spring-ai-alibaba-studio/src/main/resources/openapi.yaml, spring-ai-alibaba-studio/ui/src/pages/run/models/Setup/Config/index.tsx, spring-ai-alibaba-studio/ui/src/services/chat_models.ts
=> studio: add requestId to resp data & add model names list

spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/pom.xml, spring-ai-alibaba-studio/pom.xml
=> add compile config

spring-ai-alibaba-autoconfigure/src/main/java/com/alibaba/cloud/ai/autoconfigure/dashscope/DashScopeAutoConfiguration.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatModel.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/DashscopeAiTestConfiguration.java
fixes https://github.com/alibaba/spring-ai-alibaba/issues/360
=> feat: update DashScopeChatModel toolFunctionCallbacks auto configuration logic

community/document-readers/huggingface-fs-document-reader/README.md, community/document-readers/huggingface-fs-document-reader/pom.xml, community/document-readers/huggingface-fs-document-reader/src/main/java/com/alibaba/cloud/ai/reader/huggingface/fs/HuggingFaceFSDocumentReader.java, community/document-readers/huggingface-fs-document-reader/src/test/java/com/alibaba/cloud/ai/reader/huggingface/fs/HuggingFaceFSDocumentReaderTests.java, pom.xml
Implemented a new document reader component for reading and parsing HuggingFace dataset files.
实现了一个新的文档阅读器组件，用于读取和解析HuggingFace数据集文件。
Main changes include / 主要变更包括：
- Added `HuggingFaceFSDocumentReader` class to support JSONL and GZIP file formats
新增 `HuggingFaceFSDocumentReader` 类，支持读取JSONL和GZIP格式文件
- Implemented `DocumentReader` interface for seamless integration with Spring AI
实现了 `DocumentReader` 接口，与Spring AI文档体系无缝集成
- Provided comprehensive unit tests including local file reading tests
提供了全面的单元测试，包括本地文件读取测试
- Added detailed README documentation with usage examples and best practices
添加了详细的README文档，包含使用示例和最佳实践
- Support for reading JSON Lines format files
支持读取JSON Lines格式文件
- Automatic decompression of GZIP files
支持GZIP压缩文件的自动解压
- Automatic skipping of invalid JSON lines …
=> feat(document-readers): Add HuggingFace File System Document Reader / 添加 HuggingFace 文件系统文档阅读器 related issue:#283

spring-ai-alibaba-dependencies/pom.xml
=> :busts_in_silhouette: Function-calling dependencies

spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/pnpm-lock.yaml, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/pages/Graph/Design/FormDrawer/EndNodeForm/index.tsx, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/pages/Graph/Design/FormDrawer/StartNodeForm/index.tsx, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/pages/Graph/Design/FormDrawer/common/NextStepNodes.tsx, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/pages/Graph/Design/FormDrawer/index.tsx, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/pages/Graph/Design/GraphMap.tsx, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/pages/Graph/Design/types/BranchNode.tsx, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/pages/Graph/Design/types/CodeNode.tsx, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/pages/Graph/Design/types/CustomNode.tsx, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/pages/Graph/Design/types/DefaultNode.tsx, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/pages/Graph/Design/types/EndNode.tsx, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/pages/Graph/Design/types/KnowledgeRetrievalNode.tsx, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/pages/Graph/Design/types/LLMNode.tsx, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/pages/Graph/Design/types/StartNode.tsx, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/pages/Graph/Design/types/VariableAggregatorNode.tsx, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/store/GraphState.ts
Implement the UI and state of the forms of Start Node and End Node, and something else about them：
https://github.com/user-attachments/assets/9a0d5143-513e-4e39-9488-a16b641412c7
(For the UI, We may make it look better in near future version...)
NONE
- Implement the form data management of Start and End Node.
- Some common util function for form data management
- ***Remove formily***, for the concerns about its maintenance activity and compatibility with newer versions of Ant Design, as well as the complexity encountered while implementing certain features. 
As the video displayed.
The LLM and Branch Node will be supported soon..
=> [Graph-Studio-Workflow]: The Form of Start and End Node

.licenserc.yaml, community/document-readers/email-document-reader/pom.xml, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatModel.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatOptions.java
=> feat: add proxy_tool_calls

community/document-readers/mongodb-document-reader/pom.xml, community/document-readers/mongodb-document-reader/src/main/java/com/alibaba/cloud/ai/reader/mongodb/MongodbDocumentReader.java, community/document-readers/mongodb-document-reader/src/main/java/com/alibaba/cloud/ai/reader/mongodb/MongodbResource.java, community/document-readers/mongodb-document-reader/src/main/java/com/alibaba/cloud/ai/reader/mongodb/converter/DefaultDocumentConverter.java, community/document-readers/mongodb-document-reader/src/main/java/com/alibaba/cloud/ai/reader/mongodb/converter/DocumentConverter.java, community/document-readers/mongodb-document-reader/src/test/java/com/alibaba/cloud/ai/reader/mongodb/MongodbDocumentReaderIT.java
添加MongoDB文档阅读器实现，支持从MongoDB数据库中读取文档数据，扩展Spring AI Alibaba的数据源支持能力。
NONE
- 新增mongodb-document-reader模块
- 添加MongoDB相关依赖（mongodb-driver-sync, spring-data-mongodb）
- 实现MongoDB文档读取功能
- 可以自定义文档转化器
- 运行单元测试确保功能正常
- 配置MongoDB连接信息
- 使用MongoDB文档阅读器读取数据验证
- 该模块需要MongoDB环境支持
- Java版本要求：17
- 已添加必要的Spring Boot和MongoDB相关依赖
=> mongodb-reader

.github/ISSUE_TEMPLATE/bug_report.md, pom.xml, spring-ai-alibaba-autoconfigure/src/main/java/com/alibaba/cloud/ai/autoconfigure/dashscope/DashScopeAutoConfiguration.java, spring-ai-alibaba-dependencies/pom.xml
1. follow the spring ai to migrate to m6
=> [feat]: migrate spring-ai-alibaba 1.0.0-m5 to 1.0.0-m6

.github/ISSUE_TEMPLATE/bug_report.md, pom.xml, spring-ai-alibaba-autoconfigure/src/main/java/com/alibaba/cloud/ai/autoconfigure/dashscope/DashScopeAutoConfiguration.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/DashScopeApi.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatModel.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/observation/DashScopeChatModelObservationConvention.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/metadata/DashScopeAiUsage.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/rag/DashScopeCloudStore.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/rag/DashScopeDocumentRetrievalAdvisor.java
1. support spring-ai-alibaba use spring-ai 1.0.0-m6
=> [WIP MIGRATE]: migrate spring-ai-alibaba to 1.0.0-m6

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatOptions.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/rag/DashScopeDocumentRetrieverOptions.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/evaluation/AnswerCorrectnessEvaluator.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/evaluation/AnswerFaithfulnessEvaluator.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/evaluation/AnswerRelevancyEvaluator.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/advisor/DocumentRetrievalAdvisorTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/advisor/RetrievalRerankAdvisorTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/agent/DashScopeAgentOptionsTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/agent/DashScopeAgentTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/rag/DashScopeDocumentRetrieverOptionsTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/evaluation/AnswerCorrectnessEvaluatorTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/evaluation/AnswerFaithfulnessEvaluatorTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/evaluation/AnswerRelevancyEvaluatorTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/model/RerankRequestTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/model/RerankResponseMetadataTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/model/RerankResponseTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/model/RerankResultMetadataTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/prompt/ConfigurablePromptTemplateFactoryTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/prompt/ConfigurablePromptTemplateTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/transformer/splitter/SentenceSplitterTests.java
Implementation Details
Used Mockito for mocking dependencies
Added comprehensive assertions using AssertJ
Included edge case testing
Added detailed test documentation
Followed test naming conventions
Used StepVerifier for reactive streams testing
Testing
All tests pass successfully with good coverage. Key metrics:
Test methods: 25+
Line coverage: ~90%
Branch coverage: ~85%
=> Add Some Test Cases for DashScope Components

community/vector-stores/spring-ai-alibaba-opensearch-store/pom.xml, community/vector-stores/spring-ai-alibaba-opensearch-store/src/main/java/com/alibaba/cloud/ai/vectorstore/opensearch/OpenSearchApi.java, community/vector-stores/spring-ai-alibaba-opensearch-store/src/main/java/com/alibaba/cloud/ai/vectorstore/opensearch/OpenSearchVector.java, community/vector-stores/spring-ai-alibaba-opensearch-store/src/main/java/com/alibaba/cloud/ai/vectorstore/opensearch/OpenSearchVectorStoreOptions.java, community/vector-stores/spring-ai-alibaba-tair-store/src/main/java/com/alibaba/cloud/ai/vectorstore/tair/TairVectorStore.java, community/vector-stores/spring-ai-alibaba-tair-store/src/main/java/com/alibaba/cloud/ai/vectorstore/tair/TairVectorStoreOptions.java, pom.xml
Add OpenSearch and Tair vectorstore implementations.
=> Add VectorStore implementations

community/memory/spring-ai-alibaba-mysql-memory/pom.xml, community/memory/spring-ai-alibaba-mysql-memory/src/main/java/com/alibaba/cloud/ai/memory/mysql/MysqlChatMemory.java, community/memory/spring-ai-alibaba-redis-memory/pom.xml, community/memory/spring-ai-alibaba-redis-memory/src/main/java/com/alibaba/cloud/ai/memory/redis/RedisChatMemory.java, pom.xml, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatModel.java, spring-ai-alibaba-dependencies/pom.xml
refer to https://github.com/alibaba/spring-ai-alibaba/pull/207
=> Add ChatMemory impls

community/document-parsers/document-parser-multi-modality/src/test/java/com/alibaba/cloud/ai/parser/multi/ImageDashScopeParserTest.java, community/document-parsers/document-parser-multi-modality/src/test/java/com/alibaba/cloud/ai/parser/multi/SttDashScopeParserTest.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/api/DashScopeAgentApiTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatIT.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatModelTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeMultiModalChatTests.java
Unify the names of the keys and add IT use cases for chat.
=> Unify the names of the keys and add IT use cases for chat.

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/OverAllState.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/serializer/plain_text/PlainTextStateSerializer.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/StateGraphFileSystemPersistenceTest.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/StateGraphPersistenceTest.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/StateGraphTest.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/plain_text/gson/GSonSerializerTest.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/plain_text/jackson/JacksonSerializerTest.java
fix serialize error
fix serialize bug
see com.alibaba.cloud.ai.graph.serializer.plain_text.PlainTextStateSerializer#getStateType
see com.alibaba.cloud.ai.graph.plain_text.gson.GSonSerializerTest and com.alibaba.cloud.ai.graph.plain_text.jackson.JacksonSerializerTest
=> :busts_in_silhouette: Bugfix

CONTRIBUTING-zh.md, CONTRIBUTING.md, README-zh.md
- Updated Code Contribution Guidelines
- Update README-zh.md
Use browser to access
=> feat: Update CONTRIBUTING.md

spring-ai-alibaba-studio/ui/src/pages/run/clients/index.tsx, spring-ai-alibaba-studio/ui/src/pages/run/models/index.tsx
=> fix test errors

spring-ai-alibaba-examples/cli-debug-example/pom.xml, spring-ai-alibaba-examples/cli-debug-example/src/main/java/com/alibaba/cloud/ai/example/cli/clidebugexample/function/MockWeatherService.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/StateGraph.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/StateGraphTest.java
dependencies and test
fix compile error
see commit change
=> :bug: Fixbugs

community/vector-stores/spring-ai-alibaba-analyticdb-store/pom.xml, community/vector-stores/spring-ai-alibaba-opensearch-store/pom.xml, community/vector-stores/spring-ai-alibaba-opensearch-store/src/main/java/com/alibaba/cloud/ai/vectorstore/opensearch/OpenSearchApi.java, community/vector-stores/spring-ai-alibaba-opensearch-store/src/main/java/com/alibaba/cloud/ai/vectorstore/opensearch/OpenSearchVector.java, community/vector-stores/spring-ai-alibaba-tair-store/pom.xml, community/vector-stores/spring-ai-alibaba-tair-store/src/main/java/com/alibaba/cloud/ai/vectorstore/tair/TairVectorStore.java, spring-ai-alibaba-dependencies/pom.xml, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/pom.xml, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/checkpoint/savers/MongoSaver.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/checkpoint/savers/RedisSaver.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/StateGraphTest.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/service/dsl/nodes/VariableAggregatorNodeDataConverter.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/service/impl/ChatModelDelegateImpl.java
use jackson instead fastjson
Fixes #456
I've used the `mvn clean package` verification, but don't know much about the specifics of the business, so I can't test it at the moment.
=> fix: CVE-2022-25845 use jackson instead fastjson (#456)

spring-ai-alibaba-starter/pom.xml
=> fix ci errors

README-zh.md
Fix the problem of incorrect display of Chinese documents.
=> [Doc] Fix README

community/document-readers/spring-ai-alibaba-starter-document-reader-arxiv/src/main/java/com/alibaba/cloud/ai/reader/arxiv/client/ArxivClient.java, community/document-readers/spring-ai-alibaba-starter-document-reader-arxiv/src/test/java/com/alibaba/cloud/ai/reader/arxiv/ArxivClientTest.java
=> Optimize: arxiv pagination

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/DashScopeAudioTranscriptionApi.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/audio/DashScopeAudioTranscriptionModel.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/protocol/DashScopeWebSocketClient.java
issue: https://github.com/springaialibaba/spring-ai-alibaba-examples/issues/80
=> fix: realtime asr issue

community/openmanus/src/main/java/com/alibaba/cloud/ai/example/manus/config/QueryCommandRunner.java
feat: openmanus support input multiple plans
=> feat: openmanus support input multiple plans

community/openmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/Bash.java, community/openmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/BrowserUseTool.java, community/openmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/DocLoaderTool.java, community/openmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/FileSaver.java, community/openmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/GoogleSearch.java, community/openmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/PlanningTool.java, community/openmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/PythonExecute.java, community/openmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/PythonExecute2.java
此 PR 将tools里面的 变量使用代码块（"""）包裹，使其结构更清晰，易于阅读和维护。
修改了所有tools下的json parameters的描述 
确保没有编译错误。
=> feat: 优化工具参数和描述格式，提升代码可读性

community/document-readers/spring-ai-alibaba-starter-document-reader-bilibili/src/main/java/com/alibaba/cloud/ai/reader/bilibili/BilibiliDocumentReader.java, community/openmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/support/serpapi/SerpApiService.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-weather/src/main/java/com/alibaba/cloud/ai/toolcalling/weather/WeatherService.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/action/AsyncEdgeAction.java
This PR introduces improvements to the code by replacing the magic number 5 * 1024 * 1024 with constants that improve the readability and maintainability of the code. By defining MEMORY_SIZE and BYTE_SIZE, and using these constants to compute MAX_MEMORY_SIZE, the code is now easier to understand and modify in the future.
NONE
I created three constants MEMORY_SIZE which describes the size of the memory in the megabytes (set to 5), BYTE_SIZE which describes the number of bytes (set to 1024) and MAX_MEMORY_SIZE combines the MEMORY_SIZE and BYTE_SIZE to calculate the maximum memory size in bytes. These changes make the memory size configuration more flexible and clear in terms of its meaning.
- Check the formatting issue by running the mvn clean package command
- Test the memory related …
=> Introduce the explaning variables for better code quality

community/document-readers/spring-ai-alibaba-starter-document-reader-youtube/src/main/java/com/alibaba/cloud/ai/reader/youtube/YoutubeDocumentReader.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-bingsearch/src/main/java/com/alibaba/cloud/ai/toolcalling/bingsearch/BingSearchService.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-duckduckgo/src/main/java/com/alibaba/cloud/ai/functioncalling/duckduckgo/DuckDuckGoQueryNewsService.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-serpapi/src/main/java/com/alibaba/cloud/ai/toolcalling/serpapi/SerpApiService.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-sinanews/src/main/java/com/alibaba/cloud/ai/toolcalling/sinanews/SinaNewsService.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-toutiaonews/src/main/java/com/alibaba/cloud/ai/toolcalling/toutiaonews/ToutiaoNewsSearchHotEventsService.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-youdaotranslate/src/main/java/com/alibaba/cloud/ai/toolcalling/youdaotranslate/YoudaoTranslateService.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/DashScopeAudioTranscriptionApi.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/rag/DashScopeDocumentTransformer.java
This PR introduces improvements to the code by replacing the magic number 5 * 1024 * 1024 with constants that improve the readability and maintainability of the code. By defining MEMORY_SIZE and BYTE_SIZE, and using these constants to compute MAX_MEMORY_SIZE, the code is now easier to understand and modify in the future.
It refactors the complex conditional statements for clarity and improves the naming conventions of the variable to make it more intutive and easy to understand.
These changes enhance the code’s usability and reduce potential confusion for future developers.
NONE
1. Adding meaningful variable name :
I created three constants MEMORY_SIZE which describes the size of the memory in the megabytes (set to 5), BYTE_SIZE which describes the number of bytes (set to 1024) and …
=> Refactor the code, add explaining vars, rename vars and improve the logic

GOVERNANCE.md, community/tool-calls/spring-ai-alibaba-starter-tool-calling-toutiaonews/src/main/java/com/alibaba/cloud/ai/toolcalling/toutiaonews/ToutiaoNewsAutoConfiguration.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-toutiaonews/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/rag/DashScopeDocumentCloudReader.java
Fix typos
None
Fix typos
Not applicable.
=> refactor: fix typos in comments and documentation

community/document-readers/spring-ai-alibaba-starter-document-reader-sqlite/README.md, community/document-readers/spring-ai-alibaba-starter-document-reader-sqlite/pom.xml, community/document-readers/spring-ai-alibaba-starter-document-reader-sqlite/src/main/java/com/alibaba/cloud/ai/reader/sqlite/SQLiteDocumentReader.java, community/document-readers/spring-ai-alibaba-starter-document-reader-sqlite/src/main/java/com/alibaba/cloud/ai/reader/sqlite/SQLiteResource.java, community/document-readers/spring-ai-alibaba-starter-document-reader-sqlite/src/test/java/com/alibaba/cloud/ai/reader/sqlite/SQLiteDocumentReaderTest.java
A Reader for SQLite with SQLite4j in pure JAVA without JNI
For Reading SQLite DB files inside the JVM
use the MySQL Reader as Example Project
=> Adding a Reader for SQLite with SQLite4j in pure JAVA without JNI

README-ja.md, README-zh.md, README.md
I created Japanese translated README.
=> docs: add Japanese README

README-zh.md
=> feat: fix version number error

README.md
=> docs: fix-typo

community/openmanus/pom.xml, community/openmanus/src/main/java/com/alibaba/cloud/ai/example/manus/service/ChromeDriverService.java
=> build(openmanus): 添加 Chrome WebDriver 自动管理

pom.xml
add sensitivefilter to pom.xml
=> add sensitivefilter to pom.xml

community/tool-calls/spring-ai-alibaba-starter-tool-calling-baidumap/src/main/java/com/alibaba/cloud/ai/toolcalling/baidumap/BaiDuMapAutoConfiguration.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-baidumap/src/main/java/com/alibaba/cloud/ai/toolcalling/baidumap/BaiDuMapProperties.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-baidutranslate/src/main/java/com/alibaba/cloud/ai/toolcalling/baidutranslate/BaiduTranslateAutoConfiguration.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-baidutranslate/src/main/java/com/alibaba/cloud/ai/toolcalling/baidutranslate/BaiduTranslateProperties.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-baidutranslate/src/main/java/com/alibaba/cloud/ai/toolcalling/baidutranslate/BaiduTranslateService.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-common/src/main/java/com/alibaba/cloud/ai/toolcalling/common/CommonToolCallAutoConfiguration.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-common/src/main/java/com/alibaba/cloud/ai/toolcalling/common/CommonToolCallProperties.java
add a common method for tool-call/common module
No
Implement a method in CommonProperties to be invoked by derived Properties classes via @PostConstruct annotation.
=> feat: read default properties from system env

community/tool-calls/spring-ai-alibaba-starter-tool-calling-regex/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-regex/src/test/java/com/alibaba/cloud/ai/toolcalling/regex/RegexServiceTest.java
=> feat: Add regex tool unit test

community/tool-calls/spring-ai-alibaba-starter-tool-calling-baidusearch/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-baidusearch/src/test/java/com/alibaba/cloud/ai/toolcalling/baidusearch/BaiduSearchServiceTest.java
improve: Add baidu tool test code
=> improve: Add baidu tool test code 

community/tool-calls/spring-ai-alibaba-starter-tool-calling-baidusearch/src/main/java/com/alibaba/cloud/ai/toolcalling/baidusearch/BaiduSearchService.java
1. Support multiple User Agents to prevent anti-crawling.
2. Support configuring timeout time.
=> feat: BaiduSearchService support dynamic user agent and set timeout

spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/README.md, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/pom.xml, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/NacosMcpRegister.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/NacosMcpRegistryAutoConfigration.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/NacosMcpRegistryProperties.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/model/McpServerInfo.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/model/McpToolsInfo.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/model/RemoteServerConfigInfo.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/model/ServiceRefInfo.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/model/ToolMetaInfo.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/utils/JsonUtils.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/resources/META-INF/spring-configuration-metadata.json, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
Support mcp server auto register to nacos
=> Support mcp server auto register to nacos

community/tool-calls/spring-ai-alibaba-starter-tool-calling-baidusearch/src/test/java/com/alibaba/cloud/ai/toolcalling/baidusearch/BaiduSearchServiceTest.java
Because anti crawling is temporarily unsuccessful, disable this method first and enable it after it is fixed.
=> disable baidu test

spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/NacosMcpRegister.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/model/McpServerInfo.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/model/RemoteServerConfigInfo.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/model/ServiceRefInfo.java
Update nacos mcp register protocol
=> Update nacos mcp register protocol

.github/workflows/build-and-test.yml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-youdaotranslate/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-youdaotranslate/src/test/java/com/alibaba/cloud/ai/toolcalling/youdaotranslate/YoudaoTranslateServiceTest.java
=> Improve: Add youdao test

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/DashScopeImageApi.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/image/DashScopeImageModel.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/image/DashScopeImageOptions.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/api/DashScopeImageApiTests.java
The model Options parameters in the project need to be aligned, because the Bailian model platform is always updated, and some parameters have been obsolete, and need to be updated and aligned. The parameters of the image model need to be adjusted;
Fixes #656
According to the HTTP request specifications of the Bailian platform, update the DashscopeImageOptions by adding some commonly used model parameters, and modify the request parameters and URL on the model class side to simultaneously adapt to both text2image and image2image models.
write an example to call an AI image model with DashScopeImageModel and the updated DashScopeImageOptions to verify that the new options work
=> Adjust the parameters of DashscopeImageOptions and update the URL of the ImageModel's request

community/tool-calls/spring-ai-alibaba-starter-tool-calling-sinanews/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-sinanews/src/main/java/com/alibaba/cloud/ai/toolcalling/sinanews/SinaNewsService.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-sinanews/src/test/java/com/alibaba/cloud/ai/toolcalling/sinanews/SinaNewsServiceTest.java
=> improve: Add sinanews test

community/openmanus/src/main/java/com/alibaba/cloud/ai/example/manus/config/startUp/McpService.java
=> Fix studio mcp model parse

spring-ai-alibaba-graph/spring-ai-alibaba-graph-example/src/main/java/com/alibaba/cloud/ai/example/graph/openmanus/tool/Bash.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-example/src/main/java/com/alibaba/cloud/ai/example/graph/openmanus/tool/BrowserUseTool.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-example/src/main/java/com/alibaba/cloud/ai/example/graph/openmanus/tool/DocLoaderTool.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-example/src/main/java/com/alibaba/cloud/ai/example/graph/openmanus/tool/FileSaver.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-example/src/main/java/com/alibaba/cloud/ai/example/graph/openmanus/tool/GoogleSearch.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-example/src/main/java/com/alibaba/cloud/ai/example/graph/openmanus/tool/PythonExecute.java
=> Normalize the constants in the Openmanus graph example

spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/NacosMcpRegister.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/NacosMcpRegistryProperties.java
Mcp nacos support args description dynamic changed
=> Mcp nacos support args description dynamic changed

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/DashScopeApi.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/rag/DashScopeDocumentRetrieverOptions.java
https://github.com/alibaba/spring-ai-alibaba/issues/487 
https://help.aliyun.com/zh/model-studio/how-to-use-search-filters?spm=a2c4g.11186623.help-menu-search-2400256.d_0
=>  DashScopeApi 增加对 SearchFilters 参数的支持 ..

spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/README.md, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/NacosMcpRegister.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/NacosMcpRegistryProperties.java
Nacos mcp server auto register logic optimize
=> Nacos mcp server auto register logic optimize

spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/agent/BaseAgent.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/startupAgent/DBrowserAgent.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/startupAgent/DBrowserAgent_bak, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/startupAgent/DDefaultAgent.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/startupAgent/DDefaultAgent_bak, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/startupAgent/DTextFileAgent.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/startupAgent/DTextFileAgent_bak, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/planning/model/vo/ExecutionPlan.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/bash/Bash.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/browser/BrowserUseTool.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/textOperator/TextFileOperator.java, spring-ai-alibaba-jmanus/src/main/resources/static/admin/index.html
把agent 和内部的所有prompt都换成中文的，方便大家理解agent做什么的 。
=> Chinese agent

README-zh.md, README.md, spring-ai-alibaba-jmanus/README-zh.md, spring-ai-alibaba-jmanus/README.md
enhance the readme of jmanus .
=>  Feature/readme

community/tool-calls/spring-ai-alibaba-starter-tool-calling-common/src/main/java/com/alibaba/cloud/ai/toolcalling/common/WebClientTool.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-weather/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-weather/src/main/java/com/alibaba/cloud/ai/toolcalling/weather/WeatherAutoConfiguration.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-weather/src/main/java/com/alibaba/cloud/ai/toolcalling/weather/WeatherProperties.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-weather/src/main/java/com/alibaba/cloud/ai/toolcalling/weather/WeatherService.java
[feat] using tool calling common to refactor tool calling weather
using tool calling common to refactor tool calling weather
run spring-ai-alibaba-starter-tool-calling-weather
=> [feat] using tool calling common to refactor tool calling weather

spring-ai-alibaba-graph/spring-ai-alibaba-graph-example/src/main/java/com/alibaba/cloud/ai/example/graph/openmanus/OpenmanusController.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-example/src/main/java/com/alibaba/cloud/ai/example/graph/openmanus/human/OpenmanusHumanController.java
fix error occurred during startup
```java
Parameter 0 of constructor in com.alibaba.cloud.ai.example.graph.openmanus.human.OpenmanusHumanController required a single bean, but 2 were found:
- dashscopeChatModel: defined by method 'dashscopeChatModel' in class path resource [com/alibaba/cloud/ai/autoconfigure/dashscope/DashScopeAutoConfiguration$DashScopeChatConfiguration.class]
- openAiChatModel: defined by method 'openAiChatModel' in class path resource [org/springframework/ai/autoconfigure/openai/OpenAiAutoConfiguration.class]
```
=> fix: fix error occurred during startup

community/tool-calls/spring-ai-alibaba-starter-tool-calling-baidusearch/src/main/java/com/alibaba/cloud/ai/toolcalling/baidusearch/BaiduSearchService.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-baidusearch/src/test/java/com/alibaba/cloud/ai/toolcalling/baidusearch/BaiduSearchServiceTest.java
=> fix baidu tool

spring-ai-alibaba-jmanus/script/start_jmanus.bat, spring-ai-alibaba-jmanus/script/stop_jmanus.bat, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/browser/ChromeDriverService.java, spring-ai-alibaba-jmanus/src/main/resources/application.yml, spring-ai-alibaba-jmanus/src/main/resources/logback-spring.xml
=> 修复jar包启动无法获取jar包内部的ChromeDriver资源，添加日志输出脚本，添加windows端的jmanus的启动和停止脚本

spring-ai-alibaba-jmanus/script/start_jmanus.bat, spring-ai-alibaba-jmanus/script/stop_jmanus.bat, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/browser/ChromeDriverService.java
=> [fix] fix file license

community/memories/spring-ai-alibaba-jdbc-memory/pom.xml, community/memories/spring-ai-alibaba-jdbc-memory/src/main/java/com/alibaba/cloud/ai/memory/jdbc/JdbcChatMemoryRepository.java, community/memories/spring-ai-alibaba-jdbc-memory/src/main/java/com/alibaba/cloud/ai/memory/jdbc/SQLiteChatMemoryRepository.java, community/memories/spring-ai-alibaba-jdbc-memory/src/test/java/com/alibaba/cloud/ai/memory/jdbc/SQLiteChatMemoryRepositorySQLiteIT.java, spring-ai-alibaba-auto-configurations/pom.xml, spring-ai-alibaba-auto-configurations/src/main/java/com/alibaba/cloud/ai/autoconfigure/memory/ChatMemoryAutoConfiguration.java, spring-ai-alibaba-auto-configurations/src/main/java/com/alibaba/cloud/ai/autoconfigure/memory/SQLiteChatMemoryAutoConfiguration.java, spring-ai-alibaba-auto-configurations/src/main/java/com/alibaba/cloud/ai/autoconfigure/memory/SQLiteChatMemoryProperties.java
- For #786
update sqlite chat memory
=> feat: update sqlite chat memory

community/tool-calls/spring-ai-alibaba-starter-tool-calling-common/src/main/java/com/alibaba/cloud/ai/toolcalling/common/CommonToolCallConstants.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos-client/pom.xml, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos-client/src/main/java/com/alibaba/cloud/ai/mcp/nacos/client/NacosMcpToolCallbackAutoConfiguration.java
[fix] fix spring ai mcp version to m8
fix spring ai mcp version to m8
=> [fix] fix spring ai mcp version to m8

community/memories/spring-ai-alibaba-jdbc-memory/README.md, community/memories/spring-ai-alibaba-redis-memory/README.md
=> [Doc] add chat memory doc

community/memories/spring-ai-alibaba-jdbc-memory/src/test/java/com/alibaba/cloud/ai/memory/jdbc/MysqlChatMemoryTest.java, community/memories/spring-ai-alibaba-jdbc-memory/src/test/java/com/alibaba/cloud/ai/memory/jdbc/OracleChatMemoryTest.java, community/memories/spring-ai-alibaba-jdbc-memory/src/test/java/com/alibaba/cloud/ai/memory/jdbc/PostgresChatMemoryTest.java, community/memories/spring-ai-alibaba-jdbc-memory/src/test/java/com/alibaba/cloud/ai/memory/jdbc/SQLiteChatMemoryTest.java, community/memories/spring-ai-alibaba-jdbc-memory/src/test/java/com/alibaba/cloud/ai/memory/jdbc/SqlServerChatMemoryTest.java, spring-ai-alibaba-auto-configurations/pom.xml, spring-ai-alibaba-auto-configurations/src/main/java/com/alibaba/cloud/ai/autoconfigure/dashscope/DashScopeAutoConfiguration.java, spring-ai-alibaba-bom/pom.xml, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatModel.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatOptions.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/observation/DashScopeChatModelObservationConvention.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/embedding/DashScopeEmbeddingModel.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatIT.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatModelTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatOptionsTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeMultiModalChatTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/chat/observation/DashScopeChatModelObservationConventionTests.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/agent/ReactAgent.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/agent/ReactAgentWithHuman.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/node/ToolNode.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-example/src/main/java/com/alibaba/cloud/ai/example/graph/openmanus/tool/Builder.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/function/AgentFunctionCallbackWrapper.java
=> feat(m8): upgrade to spring-ai M8

.gitignore, pom.xml, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos-common/src/main/java/com/alibaba/cloud/ai/mcp/nacos/common/NacosMcpRegistryProperties.java, tools/make/java.mk, tools/src/checkstyle/checkstyle-suppressions.xml, tools/src/checkstyle/checkstyle.xml
=> style: update checkstyle pluign config and  add make target

community/memories/spring-ai-alibaba-jdbc-memory/pom.xml, community/memories/spring-ai-alibaba-redis-memory/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-alitranslate/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-amap/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-baidumap/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-baidusearch/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-baidutranslate/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-bingsearch/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-common/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-crawler/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-dingtalk/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-duckduckgo/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-githubtoolkit/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-googletranslate/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-microsofttranslate/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-weather/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-youdaotranslate/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-yuque/pom.xml, community/vector-stores/spring-ai-alibaba-starter-analyticdb-store/pom.xml, community/vector-stores/spring-ai-alibaba-starter-oceanbase-store/pom.xml, community/vector-stores/spring-ai-alibaba-starter-opensearch-store/pom.xml, community/vector-stores/spring-ai-alibaba-starter-tair-store/pom.xml, spring-ai-alibaba-auto-configurations/pom.xml, spring-ai-alibaba-bom/pom.xml
=> feat: format artifact id

spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/config/ConfigController.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/controller/ManusController.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/controller/PlanTemplateController.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/controller/AgentController.java
在 IDEA 2025 版本，编译期 parameters 参数存在不会携带的情况，会导致 Springboot 3 在处理 controller 时，如果未定义 name 会报错
=> Fix jmanus not work on IDEA 2025

community/tool-calls/spring-ai-alibaba-starter-tool-calling-baidusearch/src/main/java/com/alibaba/cloud/ai/toolcalling/baidusearch/BaiduSearchService.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-baidusearch/src/test/java/com/alibaba/cloud/ai/toolcalling/baidusearch/BaiduSearchServiceTest.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/node/HttpNode.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/node/HttpNodeTest.java
=> fix: fix test failed

spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/DynamicAgent.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/planning/creator/PlanCreator.java
m8接口变了， tools 不能用，换一个。 只做这一个 修改
=> fix: M8 兼容

community/memories/spring-ai-alibaba-jdbc-memory/README.md
fix doc error ,lastest dep is spring-ai-alibaba-starter-memory-jdbc but doc is old
=> fix spring-ai-alibaba-starter-memory-jdbc doc

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/node/LlmNode.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-example/src/main/java/com/alibaba/cloud/ai/example/graph/bigtool/agent/CalculateAgent.java
=> 修复 LlmNode 和 CalculateAgent 中的工具回调方法名，将 `tools` 更改为 `toolCallbacks`。

spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos-client/src/main/java/com/alibaba/cloud/ai/mcp/nacos/client/NacosMcpClientAutoConfiguration.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos-client/src/main/java/com/alibaba/cloud/ai/mcp/nacos/client/NacosMcpSseClientAutoConfiguration.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos-client/src/main/java/com/alibaba/cloud/ai/mcp/nacos/client/NacosMcpToolCallbackAutoConfiguration.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos-client/src/main/java/com/alibaba/cloud/ai/mcp/nacos/client/transport/LoadbalancedMcpAsyncClient.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos-client/src/main/java/com/alibaba/cloud/ai/mcp/nacos/client/transport/LoadbalancedMcpSyncClient.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/NacosMcpRegister.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/model/McpNacosConstant.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/utils/MD5Utils.java
从nacos中获取最新的tool信息
方案文档说明：https://ik3te1knhq.feishu.cn/wiki/W8ctwG2sAiPkrXkpl7ocP0g0njf
=> pull nacos for tool

README-ja.md, README-zh.md, README.md
=> [Doc]  update readme version 

spring-ai-alibaba-auto-configurations/src/main/java/com/alibaba/cloud/ai/autoconfigure/memory/ChatMemoryAutoConfiguration.java, spring-ai-alibaba-auto-configurations/src/main/java/com/alibaba/cloud/ai/autoconfigure/memory/MysqlChatMemoryAutoConfiguration.java, spring-ai-alibaba-auto-configurations/src/main/java/com/alibaba/cloud/ai/autoconfigure/memory/OracleChatMemoryAutoConfiguration.java, spring-ai-alibaba-auto-configurations/src/main/java/com/alibaba/cloud/ai/autoconfigure/memory/PostgresChatMemoryAutoConfiguration.java, spring-ai-alibaba-auto-configurations/src/main/java/com/alibaba/cloud/ai/autoconfigure/memory/SQLiteChatMemoryAutoConfiguration.java, spring-ai-alibaba-auto-configurations/src/main/java/com/alibaba/cloud/ai/autoconfigure/memory/SqlServerChatMemoryAutoConfiguration.java
Solve some auto load problems
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'oracleChatMemoryRepository' defined in class path resource [com/alibaba/cloud/ai/autoconfigure/memory/OracleChatMemoryAutoConfiguration.class]: Failed to instantiate [com.alibaba.cloud.ai.memory.jdbc.OracleChatMemoryRepository]: Factory method 'oracleChatMemoryRepository' threw exception with message: Failed to obtain JDBC Connection
```
=> fix chat memory

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/rag/DashScopeDocumentRetrievalAdvisor.java
- For #786 
feat: compatible DashScopeDocumentRetrievalAdvisor with M8
=> feat: compatible DashScopeDocumentRetrievalAdvisor with M8

spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/service/AgentServiceImpl.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/mcp/service/McpService.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/planning/PlanningFactory.java
=> feat: load mcp service when needed to prevent connection failure

community/memories/spring-ai-alibaba-jdbc-memory/README.md
The example in the readme file is missing the content to start the autowiring
=> doc:fix the missing configuration in mysql momery's README

community/tool-calls/spring-ai-alibaba-starter-tool-calling-common/src/main/java/com/alibaba/cloud/ai/toolcalling/common/CommonToolCallUtils.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-tavilysearch/pom.xml
=> fix CommonToolCallUtils

spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/entity/DynamicAgentEntity.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/service/AgentServiceImpl.java
=> Fix jmanus not work when init db

spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/service/impl/ChatClientDelegateImpl.java
fix memory enable rc1
replace **AbstractChatMemoryAdvisor** to  **BaseChatMemoryAdvisor**
=> [fix] fix memory enable rc1

pom.xml, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/CompiledGraph.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/StateGraph.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/utils/EdgeMappings.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/StateGraphRepresentationTest.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/StateGraphTest.java
add Representation Unit
none
see com.alibaba.cloud.ai.graph.StateGraphRepresentationTest
see com.alibaba.cloud.ai.graph.StateGraphRepresentationTest
=> :busts_in_silhouette: Representation Unit

community/tool-calls/spring-ai-alibaba-starter-tool-calling-tavilysearch/src/main/java/com/alibaba/cloud/ai/toolcalling/tavily/TavilySearchAutoConfiguration.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-tavilysearch/src/main/java/com/alibaba/cloud/ai/toolcalling/tavily/TavilySearchProperties.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-tavilysearch/src/main/java/com/alibaba/cloud/ai/toolcalling/tavily/TavilySearchService.java
=> refactor(tavilysearch):refactor TavilySearch call tool module

auto-configurations/spring-ai-alibaba-autoconfigure-nacos-mcp-client/src/main/java/com/alibaba/cloud/ai/autoconfigure/mcp/client/NacosMcpClientAutoConfiguration.java, auto-configurations/spring-ai-alibaba-autoconfigure-nacos-mcp-client/src/main/java/com/alibaba/cloud/ai/autoconfigure/mcp/client/NacosMcpSseClientAutoConfiguration.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/client/transport/LoadbalancedMcpAsyncClient.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/client/transport/LoadbalancedMcpSyncClient.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/registry/NacosMcpRegister.java
1. 修复缺失Nacos命名空间配置
2. mcp旧版本0.9升级到0.10的调整
=> fix nacos-mcp

README-ja.md, README-zh.md, README.md
add deepwiki badge, for enabling auto refresh
=> [feat] add deepwiki badge

pom.xml, spring-ai-alibaba-bom/pom.xml, spring-ai-alibaba-mcp/pom.xml, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/pom.xml, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/dynamic/server/config/NacosMcpDynamicProperties.java
modify module pom
for mcp nacos
=> [refactor] modify module pom

spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/pages/Graph/index.tsx
modify graph studio default saa version to 1.0.0.1
=> [refactor] modify graph studio default saa version

.github/workflows/build-and-test.yml, .github/workflows/license-check.yml, .github/workflows/linter.yml
=> [feat] add ci if

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/pom.xml, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/StateGraphStreamTest.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/stream/LLmNodeAction.java
update open ai api
none
see com.alibaba.cloud.ai.graph.stream.LLmNodeAction
see com.alibaba.cloud.ai.graph.stream.LLmNodeAction
=> :white_check_mark: Feat(graph):update open ai api

spring-ai-alibaba-graph/spring-ai-alibaba-graph-example/src/main/resources/application.yml
=> [fix] fix api key

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/DashScopeAiStreamFunctionCallingHelper.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/DashScopeApi.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/api/DashScopeAiStreamFunctionCallingHelperTests.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/pom.xml, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/checkpoint/savers/MemorySaver.java
fix Tool calls occur error（NPE） when using stream output 
Fixes #992
=> fix: fix Tool calls occur error（NPE） when using stream output 

spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/controller/DeepResearchController.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/HumanFeedbackNode.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/PlannerNode.java
module：deep-research
feat：
About the planning Node, we can choose ：
“y”: accepted the plan
"n"&"feedback": refuse & recreate plan by feedback
=> feat: add user selection in HumanFeedbackNode

spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/client/tool/LoadbalancedAsyncMcpToolCallback.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/client/tool/LoadbalancedSyncMcpToolCallback.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/client/transport/LoadbalancedMcpAsyncClient.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/client/transport/LoadbalancedMcpSyncClient.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos2/src/main/java/com/alibaba/cloud/ai/mcp/nacos2/client/tool/LoadbalancedAsyncMcpToolCallback.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos2/src/main/java/com/alibaba/cloud/ai/mcp/nacos2/client/tool/LoadbalancedSyncMcpToolCallback.java
一个ToolCallback对应的ToolDefinition的name应该是保持不变的，现阶段因为取的clientInfo的name是会变化的，因为绑定了多个实例
=> fix: fix name

spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/registry/NacosMcpRegister.java
Fix the bug of different version of mcp servers will register to same service in Nacos
=> fix(mcp): fix the bug of different version of mcp servers register to same service in Nacos

spring-ai-alibaba-deepresearch/pom.xml, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/controller/DeepResearchController.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/PlannerNode.java
=> fix: 修复了deepresearch跑不起来，运行报错的问题

spring-ai-alibaba-deepresearch/README-zh.md, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/BackgroundInvestigationNode.java, spring-ai-alibaba-deepresearch/src/main/resources/application.yml
1. Edited Dashscope PATH to align with other modules.
2. #1036 Bug Report 2: Added timeout parameters in application.yml
3. #1036 Bug Report 3: Fixed the issue where subsequent nodes were unable to obtain background_investation_desult.
Partly fixed #1036 
**Fix 2 test:**
**Fix 3 comparation:**
**before:**
**after:**
=> fix(deepresearch): partly fix Issue#1036 

spring-ai-alibaba-deepresearch/README-zh.md, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/controller/DeepResearchController.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/controller/graph/GraphProcess.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/controller/request/ChatRequestProcess.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/PlannerNode.java
1.  调整了一些代码结构
2. 增加 contributor
=> feat(deepresearch): adjust

package.json, spring-ai-alibaba-jmanus/ui-vue3/package.json
移除根目录下的 pkg.json 文件，将依赖放到对应的子项目下
=> chore(jmanus): remove useless file

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/CompiledGraph.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-example/src/main/java/com/alibaba/cloud/ai/example/graph/stream/LLmSearchStreamController.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-example/src/main/java/com/alibaba/cloud/ai/example/graph/stream/node/LLmNode.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-example/src/main/java/com/alibaba/cloud/ai/example/graph/stream/node/ResultNode.java
Multi key stream support
none
com.alibaba.cloud.ai.graph.CompiledGraph.AsyncNodeGenerator#getEmbedGenerator
see com.alibaba.cloud.ai.example.graph.stream.node.LLmNode
=> feat(graph): multi key stream support

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/CompiledGraph.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/node/LlmNode.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/StateGraphTest.java
Llmnode stream and command state update
Fixes #1130
com.alibaba.cloud.ai.graph.StateGraphTest#testCommandEdgeGraph
com.alibaba.cloud.ai.graph.node.LlmNode#apply
com.alibaba.cloud.ai.graph.StateGraphTest#testCommandEdgeGraph
com.alibaba.cloud.ai.graph.node.LlmNode#apply
=> feat(graph): llmnode stream support

spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/config/DeepResearchConfiguration.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/controller/DeepResearchController.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/model/req/ChatRequest.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/HumanFeedbackNode.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/PlannerNode.java
deepresearch: 
module：planNode & HumanFeedbackNode
finish: the interrupted & structured response
interface: /chat/resume
=> fix(deepresearch): the interrupted & structured response of plan&humanFeedback

spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/service/AgentServiceImpl.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/mcp/service/McpService.java
=> fix(jmanus): rebuild mcp client when requesting getAvailableTools

spring-ai-alibaba-nl2sql/chat/src/main/java/com/alibaba/cloud/ai/request/SearchRequest.java, spring-ai-alibaba-nl2sql/chat/src/main/java/com/alibaba/cloud/ai/service/analytic/AnalyticSchemaService.java, spring-ai-alibaba-nl2sql/chat/src/main/java/com/alibaba/cloud/ai/service/base/BaseSchemaService.java, spring-ai-alibaba-nl2sql/chat/src/main/java/com/alibaba/cloud/ai/service/base/BaseVectorStoreService.java, spring-ai-alibaba-nl2sql/chat/src/main/java/com/alibaba/cloud/ai/service/simple/SimpleSchemaService.java, spring-ai-alibaba-nl2sql/chat/src/main/java/com/alibaba/cloud/ai/service/simple/SimpleVectorStoreService.java
fixforeign key handling and document query logic
=> fix(nl2sql): fixforeign key handling and document query logic

spring-ai-alibaba-nl2sql/common/pom.xml
Lombok has repeatedly declared dependencies
=> fix(nl2sql): remove repeatedly lomobk.

spring-ai-alibaba-deepresearch/Dockerfile, spring-ai-alibaba-deepresearch/README-zh.md
- Add Dockerfile for deepresearch module
- Use Alibaba Dragonwell 17 Ubuntu base image build deepresearch docker image
- run docker container and check log info
- request "http://localhost:8080/deep-research/chat/stream" test
- update readme-zh file
=> feat(deepresearch): deepresearch Dockerfile

spring-ai-alibaba-nl2sql/common/pom.xml
add httpclient5 dependency for improved HTTP client
=> fix(nl2sql): add httpclient5 dependency for improved HTTP client

tools/scripts/new-line-check.py
infra(ci): Update new-line-check.py
=> infra(ci): Update new-line-check.py

COMMITTERS.md
=> docs: Add new committer

spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/pom.xml, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/config/GraphInitializrConfiguration.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/format/EclipseJdtFormatProjectContributor.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/service/generator/workflow/WorkflowProjectGenerator.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/service/generator/workflow/sections/AnswerNodeSection.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/service/generator/workflow/sections/DocumentExtractorNodeSection.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/service/generator/workflow/sections/HttpNodeSection.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/service/generator/workflow/sections/HumanNodeSection.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/service/generator/workflow/sections/KnowledgeRetrievalNodeSection.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/service/generator/workflow/sections/LLMNodeSection.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/service/generator/workflow/sections/ListOperatorNodeSection.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/service/generator/workflow/sections/MCPNodeSection.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/service/generator/workflow/sections/ParameterParsingNodeSection.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/service/generator/workflow/sections/QuestionClassifierNodeSection.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/service/generator/workflow/sections/ToolNodeSection.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/resources/templates/GraphBuilder.java.mustache
Improve the issue of hard-coded indentation used in DSL code conversion.
=> feat(graph): impl ProjectContributor to format dsl-graph code

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/streaming/AsyncGeneratorUtils.java
fix indexout error
NONE
see com.alibaba.cloud.ai.graph.streaming.AsyncGeneratorUtils#createMergedGenerator
see com.alibaba.cloud.ai.graph.streaming.AsyncGeneratorUtils#createMergedGenerator
=> fix(graph): fix indexout error

CONTRIBUTING-zh.md, CONTRIBUTING.md, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/util/StateUtil.java
Improve(core): remove unused imports and add contribute checkstyle contents
=> chore(core): unused imports

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/DashScopeApi.java
translate the Chinese comments into English.
=> feat(core): translate the Chinese comments into English.

auto-configurations/spring-ai-alibaba-autoconfigure-nacos-mcp-client/src/main/java/com/alibaba/cloud/ai/autoconfigure/mcp/client/NacosMcpToolCallbackAutoConfiguration.java
命名统一：loadbalancedMcpSyncToolCallbacks
=> fix(mcp): name

community/tool-calls/spring-ai-alibaba-starter-tool-calling-youdaotranslate/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-youdaotranslate/src/test/java/com/alibaba/cloud/ai/toolcalling/youdaotranslate/YoudaotranslateTest.java
1. add a test unit class for youdao translate
For  #1168
=> feat(tool-calls): add Youdao translate unit test

spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/service/generator/workflow/WorkflowProjectGenerator.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/resources/templates/GraphBuilder.java.mustache
adapt to the new signature of stateGraph
change OverAllStateFactory to KeyStrategyFactory
=> feat(graph): adapt to the new signature of stateGraph

spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/serializer/DeepResearchStateSerializer.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/serializer/plain_text/jackson/JacksonStateSerializer.java
update JSON serialization to use UTF-8 encoding
=> fix(core): update JSON serialization to use UTF-8 encoding

.github/workflows/build-and-test.yml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-weather/pom.xml, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/tool/PythonReplTool.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/pom.xml, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/node/code/DockerCodeExecutor.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/node/code/DockerCodeExecutorTest.java, tools/github-actions/setup-deps/action.yml, tools/src/checkstyle/checkstyle.xml
refactor(graph): 
1. remove docker httpclient5
2. add unit test for docker code action
link: https://github.com/alibaba/spring-ai-alibaba/issues/1268
=> refactor(graph): remove docker httpclient5

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/async/AsyncGenerator.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/streaming/AsyncGeneratorUtils.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/streaming/StreamingChatGenerator.java
Optimize parallel churn processing
NONE
Reduce the lock range and optimize the lock types
see com.alibaba.cloud.ai.graph.streaming.AsyncGeneratorUtils#createMergedGenerator
=> fix(graph): graph stream fix

spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/util/StateUtil.java
fix(deepresearch): correct error param
=> fix(deepresearch): correct error param

spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/agents/AgentsConfiguration.java
=> fix(deepresearch): resolve conflicts

spring-ai-alibaba-deepresearch/pom.xml, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/agents/AgentModelsConfiguration.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/CoderNode.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/ResearchTeamNode.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/ResearcherNode.java, spring-ai-alibaba-deepresearch/src/main/resources/application.yml
修复chatmodel缺失toolCallingManager，工具未生效，从而导致模型未返回响应，最终导致一直循环最大次数失败
=> fix(deepresearch): tool

spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/browser/InteractiveElement.java
=> fix(jmanus): fix code format

spring-ai-alibaba-jmanus/ui-vue3/package.json, spring-ai-alibaba-jmanus/ui-vue3/src/components/chat/index.vue, spring-ai-alibaba-jmanus/ui-vue3/src/components/plan-execution/index.vue, spring-ai-alibaba-jmanus/ui-vue3/src/components/right-panel/index.vue, spring-ai-alibaba-jmanus/ui-vue3/src/components/sidebar/index.vue, spring-ai-alibaba-jmanus/ui-vue3/src/stores/right-panel.ts, spring-ai-alibaba-jmanus/ui-vue3/src/stores/sidebar.ts, spring-ai-alibaba-jmanus/ui-vue3/src/views/direct/index.vue
- Try to correct the time when drawer open and close
=> chore(jmanus): orrectly open and close drawer

spring-ai-alibaba-nl2sql/chat/README.md
=> docs(nl2sql): update nl2sql readme

pom.xml, spring-ai-alibaba-bom/pom.xml, spring-ai-alibaba-deepresearch/pom.xml, spring-ai-alibaba-jmanus/pom.xml, spring-ai-alibaba-nl2sql/pom.xml, spring-ai-alibaba-studio/pom.xml
upgrade spotless to 2.44.5 to fix spotless build failed on jdk21
=> fix(ci): fix spotless build failed on jdk21

spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/config/DeepResearchConfiguration.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/dispatcher/RewriteAndMultiQueryDispatcher.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/BackgroundInvestigationNode.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/CoordinatorNode.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/PlannerNode.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/ReporterNode.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/RewriteAndMultiQueryNode.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/serializer/DeepResearchDeserializer.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/util/StateUtil.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/util/TemplateUtil.java
Describe what this PR does / why we need it
add a new node RewriteAndMultiQuery that can rewrite and expand query
Describe how you did it
1.add a new field optimize_queries
2.update the StateUtil to make it easier to distinguish query and optimize_queries
3.use MultiQueryExpander & RewriteQueryTransformer to impliment rewrite & multiquery
4.adjust the way to get queries in plannerNode & backgroundNode
5.adjust the way to get backgroundResults in reporterNode
6.replace add query loop to template
=> feat(deepresearch): add RewriteAndMultiQueryNode

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/pom.xml
=> fix(graph): fix pom for mvnd

community/tool-calls/README.md, community/tool-calls/spring-ai-alibaba-starter-tool-calling-duckduckgo/src/test/java/com/alibaba/cloud/ai/toolcalling/duckduckgo/DuckDuckGoTest.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-jsonprocessor/src/main/java/com/alibaba/cloud/ai/toolcalling/jsonprocessor/JsonProcessorAutoConfiguration.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-jsonprocessor/src/main/java/com/alibaba/cloud/ai/toolcalling/jsonprocessor/JsonProcessorConstants.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-jsonprocessor/src/main/java/com/alibaba/cloud/ai/toolcalling/jsonprocessor/JsonProcessorInsertService.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-jsonprocessor/src/main/java/com/alibaba/cloud/ai/toolcalling/jsonprocessor/JsonProcessorParseService.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-jsonprocessor/src/main/java/com/alibaba/cloud/ai/toolcalling/jsonprocessor/JsonProcessorRemoveService.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-jsonprocessor/src/main/java/com/alibaba/cloud/ai/toolcalling/jsonprocessor/JsonProcessorReplaceService.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-time/src/main/java/com/alibaba/cloud/ai/toolcalling/time/TimeAutoConfiguration.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-time/src/main/java/com/alibaba/cloud/ai/toolcalling/time/TimeConstants.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-time/src/main/java/com/alibaba/cloud/ai/toolcalling/time/TimeProperties.java
=> fix(tool-calls): format code and add duckduckgo unit test

spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/service/generator/workflow/sections/VariableAggregatorNodeSection.java
Add the rendering logic for the variable aggregation nodes during the DSL conversion process.
=> feat(graph): add rendering logic for variable aggregation nodes.

.github/workflows/issue-and-pr.yml
=> infra(ci): add issue and pr bot

.github/workflows/issue-and-pr.yml
=> infra(ci): update action version

pom.xml, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos-common/src/main/java/com/alibaba/cloud/ai/mcp/nacos/service/NacosMcpOperationService.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/registry/NacosMcpRegister.java
修复了Nacos MCP Server版本变更时无法成功注册到Nacos的Bug，更新Nacos sdk至3.0.2
=> fix(mcp): 修复了Nacos MCP Server版本变更时无法成功注册到Nacos的Bug

spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/README.md, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/service/simple/SimpleVectorStoreService.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/util/AiConfiguration.java
support multiple embedding models with configurable options
=> feat(nl2sql): support multiple embedding models with configurable options

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/observation/GraphObservationLifecycleListener.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/observation/edge/DefaultGraphEdgeObservationConvention.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/observation/edge/GraphEdgeObservationContext.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/observation/graph/GraphObservationContext.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/observation/node/DefaultGraphNodeObservationConvention.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/observation/node/GraphNodeObservationContext.java
Correct graph observation span relation.
NONE
Maintain the scope manually.
=> fix(graph): correct graph observation span relation

spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/service/dsl/nodes/BranchNodeDataConverter.java
=> fix(graph): modify BranchNodeDataConverter to avoid value variable registration

spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/service/generator/workflow/WorkflowProjectGenerator.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/resources/templates/GraphBuilder.java.mustache
Dynamically render import based on the node.
Mainly through obtaining the node's type for dynamic judgment and then rendering.
=> feat(graph): dynamically render the corresponding import based on the node

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/node/McpNode.java
support mcp path key
such as: 高德服务“https://mcp.amap.com/sse?key=xxx”
=> feat(graph): support mcp path key

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/CompiledGraph.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-example/src/main/java/com/alibaba/cloud/ai/example/graph/react/ReactController.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/bash/MacShellExecutor.java
update return value in shouldInterruptBefore
NONE
Change shouldInterruptBefore returns node node data
=> feat(graph): update return value in shouldInterruptBefore

spring-ai-alibaba-jmanus/ui-vue3/src/components/chat/index.vue
**Describe what this PR does / why we need it**
jmanus对话框中动态的输入组件会被全局调用的handlePlanUpdate清除对话框中的输入
**Does this pull request fix one issue?**
使用formInputsStore单独管理对话框的输入组件
**Describe how to verify it**
✅ 输入数据实时同步到 formInputsStore
✅ 提交后能正确处理多字段数据
✅ 组件卸载后 store 中对应数据被清除
✅ 重复打开/关闭表单无状态污染
**Special notes for reviews**
未打包，只提交了修改的源文件
重点关注多表单实例共存场景
=> fix(jmanus): fix time clear input issue for conditional dynamic input jmanus dialog

spring-ai-alibaba-deepresearch/README-zh.md, spring-ai-alibaba-deepresearch/pom.xml, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/controller/ChatController.java, spring-ai-alibaba-deepresearch/src/main/resources/application.yml
添加了在DeepResearch中使用Langfuse进行可观测性的能力。
方便观测每个节点的输入、输出进行调试，优化，迭代。
=> Feature/deepresearch 整合langfuse对Graph运行时内容进行观测

spring-ai-alibaba-jmanus/README-zh.md, spring-ai-alibaba-jmanus/README.md, spring-ai-alibaba-jmanus/pom.xml, spring-ai-alibaba-jmanus/src/main/resources/application-h2.yml, spring-ai-alibaba-jmanus/src/main/resources/application-mysql.yml, spring-ai-alibaba-jmanus/src/main/resources/application.yml
Support external database (MySQL)
NONE
See change code
first: 
```bash
$ application.yml
spring:
application:
name: spring-ai-alibaba-openmanus
profiles:
active: mysql # Switch database type, You can choose H2 and MySQL
```
before starting the service, a MySQL database should be created
```mysql
create database openmanus_db;
```
finally start the service
```bash
$ mvn spring-boot:run
...
2025-07-08 16:18:40.245  INFO 55370 --- [           main] c.a.c.a.e.m.c.s.AppStartupListener       : Application started, attempting to open browser to access: http://localhost:18080/ui/index.html
2025-07-08 16:18:40.266  INFO 55370 --- [           main] c.a.c.a.e.m.c.s.AppStartupListener       : Successfully opened browser via macOS open command
2025-07-08 16:18:40.415  INFO 55370 --- [io-18080-exec-1] …
```
=> feat Jmanus 支持MySQL数据库

auto-configurations/spring-ai-alibaba-autoconfigure-dashscope/src/main/java/com/alibaba/cloud/ai/autoconfigure/dashscope/DashScopeImageAutoConfiguration.java
=> fix(core): fix image config

spring-ai-alibaba-nl2sql/pom.xml, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/pom.xml, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-common/src/main/java/com/alibaba/cloud/ai/dbconnector/DbAccessor.java
=> feat(nl2sql): optimize JSON schema dependencies and clean up 

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/aot/DashScopeAIRuntimeHints.java, spring-ai-alibaba-core/src/main/resources/META-INF/spring/aot.factories
=> feat(core): add graalvm native compile support

spring-ai-alibaba-deepresearch/src/main/resources/application-observability.yml
- For https://github.com/alibaba/spring-ai-alibaba/actions/runs/16250059953/job/45878479013
=> style(deepresearch): fix deepsearch yml style

spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/README.md
=> feat(nl2sql): add nl2sql ollama doc

spring-ai-alibaba-jmanus/README-zh.md, spring-ai-alibaba-jmanus/README.md, spring-ai-alibaba-jmanus/pom.xml, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/prompt/service/PromptDataInitializer.java, spring-ai-alibaba-jmanus/src/main/resources/application-h2.yml, spring-ai-alibaba-jmanus/src/main/resources/application-mysql.yml, spring-ai-alibaba-jmanus/src/main/resources/application-postgres.yml, spring-ai-alibaba-jmanus/src/main/resources/application.yml
jmanus支持使用postgres数据库，pg真的好多好多人在用，特别是公司里面。
沿用jpa的简化特性，只不过pg需要兼容下大对象查询需要手动开启事务问题。
修改application.yml中spring.profiles.active为postgres，同时编辑application-postgres.yml为对应的数据库信息即可。
=> feat(jmanus): jmanus support PostgreSQL

spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/constant/Constant.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/node/KeywordExtractNode.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/node/PythonExecuteNode.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/node/QueryRewriteNode.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/node/ReportGeneratorNode.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/node/SchemaRecallNode.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/node/SemanticConsistencNode.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/node/SqlExecuteNode.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/node/SqlGenerateNode.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/node/SqlValidateNode.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/node/TableRelationNode.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/schema/ColumnDTO.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/schema/TableDTO.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/service/simple/SimpleVectorStoreService.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/util/ChatResponseUtil.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-management/src/main/java/com/alibaba/cloud/ai/Application.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-management/src/main/java/com/alibaba/cloud/ai/controller/AnalyticNl2SqlController.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-management/src/main/java/com/alibaba/cloud/ai/controller/HomeController.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-management/src/main/java/com/alibaba/cloud/ai/controller/Nl2sqlForGraphController.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-management/src/main/java/com/alibaba/cloud/ai/controller/SimpleChatController.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-management/src/main/resources/static/nl2sql.html
https://github.com/user-attachments/assets/7cf438e0-29c0-454b-838c-7c3469a48352
=> feat(nl2sql): support stream response

spring-ai-alibaba-jmanus/ui-vue3/src/base/i18n/en.ts, spring-ai-alibaba-jmanus/ui-vue3/src/components/chat/index.vue, spring-ai-alibaba-jmanus/ui-vue3/src/components/input/index.vue, spring-ai-alibaba-jmanus/ui-vue3/src/components/plan-execution/index.vue, spring-ai-alibaba-jmanus/ui-vue3/src/components/select/index.vue, spring-ai-alibaba-jmanus/ui-vue3/src/components/sidebar/index.vue, spring-ai-alibaba-jmanus/ui-vue3/src/components/tool-selection-modal/index.vue
- Translate src/base/ and src/components/ 
- Explicitly exclude `ui-vue3/src/base/i18n/zh.ts`
Partially fixes #1583
Located and translated.
1. Check files in src/base/ and src/components/ to confirm:
- All Chinese comments are replaced with English equivalents.
- No code logic was accidentally altered.
2. Build and test the project to ensure no unintended side effects.
Only comment translations—no functional changes.
=> feat(jmanus): translate Chinese comments to English in ui-vue3/src/base/ and ui-vue3/src/components/

spring-ai-alibaba-jmanus/ui-vue3/src/views/configs/agentConfig.vue, spring-ai-alibaba-jmanus/ui-vue3/src/views/configs/basicConfig.vue, spring-ai-alibaba-jmanus/ui-vue3/src/views/configs/index.vue, spring-ai-alibaba-jmanus/ui-vue3/src/views/configs/mcpConfig.vue, spring-ai-alibaba-jmanus/ui-vue3/src/views/configs/modelConfig.vue, spring-ai-alibaba-jmanus/ui-vue3/src/views/direct/index.vue, spring-ai-alibaba-jmanus/ui-vue3/src/views/home/index.vue
- Translate ui-vue3/src/view
#1583 
Located and translated.
Only comment translations—no functional changes.
=> feat(jmanus): translate Chinese comments to English in ui-vue3/src/view

spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/controller/AgentController.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/entity/DynamicAgentEntity.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/repository/DynamicAgentRepository.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/service/AgentConfig.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/service/AgentService.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/service/AgentServiceImpl.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/service/DynamicAgentLoader.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/service/DynamicAgentScanner.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/prompt/controller/PromptController.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/prompt/repository/PromptRepository.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/prompt/service/PromptDataInitializer.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/prompt/service/PromptService.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/prompt/service/PromptServiceImpl.java, spring-ai-alibaba-jmanus/src/main/resources/application.yml
Add a namespace function to support different prompt and agent values.
该feature是在issue中寻找的，并且和该feature发起者取得了沟通。
feature链接：https://github.com/alibaba/spring-ai-alibaba/issues/1533
（1）新增namespace表，用来存储命名空间相关信息（id、name、code、description）。
（2）prompt和agent表新增namespace字段，该值与namespace表中的code字段关联。
（3）代码中namespace的值从application.yml中获取，并用来查询对应的prompt和agent信息。
（4）
通过api接口手动测试过了
=> feat(jmanus): Add a namespace function

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/DashScopeImageApi.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/common/DashScopeApiConstants.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/api/DashScopeImageApiTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/image/observation/DashScopeImageModelObservationITests.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/service/impl/ChatModelDelegateImpl.java
- refer https://help.aliyun.com/zh/model-studio/text-to-image-v2-api-reference
=> feat(core): update image api params

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/DashScopeApi.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatModel.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/api/DashScopeAiStreamFunctionCallingHelperTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatModelTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeMultiModalChatTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/metadata/DashScopeAiUsageTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/rerank/DashScopeRerankModelTests.java
- refer https://help.aliyun.com/zh/model-studio/use-qwen-by-calling-api
=> feat(core): update dashscope chat api params

spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/registry/NacosMcpRegister.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/registry/NacosMcpRegistryProperties.java
Update Nacos mcp register logic
完善自动注册逻辑，当用户不指定注册的服务名称时，以Nacos服务端的为准
=> feat(mcp): update Nacos mcp register logic

spring-ai-alibaba-jmanus/src/main/resources/META-INF/native-image/reflect-config.json
=> fix(jmanus): fix jmanus reflect-config

spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/config/IManusProperties.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/startupAgent/IStartupAgentConfigLoader.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/planning/coordinator/IPlanIdDispatcher.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/planning/executor/factory/IPlanExecutorFactory.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/prompt/IPromptLoader.java
=> feat(jmanus): license

spring-ai-alibaba-graph/spring-ai-alibaba-graph-example/src/main/resources/application.yml
=> fix(graph): repair error description

spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/service/AgentServiceImpl.java
fix the adjustment issue regarding the namespace 
if the frontend don't set namespace  property , update the namespace to 'default'
=> fix(jmanus): add namespace handling and default namespace logic

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/transformer/splitter/RecursiveCharacterTextSplitter.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/transformer/splitter/RecursiveCharacterTextSplitterTest.java
Describe what this PR does / why we need it
添加递归字符文本切分器，中文有自己的句号，非常适合按段落、句号等标点符号进行切分，以保持语义完整性
Does this pull request fix one issue?
NONE
Describe how you did it
-通过递归方式按字符分割文本
-支持自定义块大小和分隔符
在无法进一步分割时，最终按块大小进行分割
Describe how to verify it
单元测试
Special notes for reviews
=> feat(core): add Recursive Character Text Splitter

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatModel.java
exampl: https://github.com/springaialibaba/spring-ai-alibaba-examples/pull/322
```json
{
"llm-res": "以下是关于 **Spring AI** 的详细介绍，综合了权威来源的核心内容：\n\n---\n\n### **1. 框架概述**  \nSpring AI 是由 Spring 团队维护的 Java 版 AI 应用开发框架，旨在将 Spring 生态的设计原则（如模块化、可移植性）引入 AI 领域，提供统一的 API 抽象层，支持多种 AI 模型和向量数据库[1][4][7]。其核心理念是通过 POJO（普通 Java 对象）简化 AI 应用开发，并兼容企业级需求[1][3]。\n\n### **2. 核心功能**  \n- **多模型支持**：  \n  支持主流 AI 提供商（如 OpenAI、Anthropic、Google Gemini、Ollama 等），涵盖聊天、文本生成、图像生成、语音转录等功能[1][7][9]。开发者仅需修改配置即可切换模型[4]。  \n- **向量数据库集成**：  \n  提供 PostgreSQL/PGVector、Redis、Pinecone 等数据库的适配模块，支持语义搜索和知识增强[1][5][9]。  \n- **开发工具**：  \n  - **Prompt 模板**：支持动态变量插入，类似 Spring MVC 的视图模板[3][5]。  \n  - **流式响应（Flux）**：实现类似 ChatGPT 的逐字输出效果[4][8]。  \n  - **自动配置**：通过 Spring Boot 快速集成，减少样板代码[7][8]。\n\n### **3. 典型应用场景**  \n- **聊天机器人**：通过 …
```
=> feat(core): add search_info params in metadata

spring-ai-alibaba-prompt/spring-ai-alibaba-prompt-nacos/src/test/resources/prompts/system-message.st
=> chore(prompt): fix typo

.github/workflows/build-jmanus-docker.yml, .github/workflows/build-jmanus-macos.yml, spring-ai-alibaba-jmanus/.dockerignore, spring-ai-alibaba-jmanus/Dockerfile.multiarch, spring-ai-alibaba-jmanus/README-zh.md, spring-ai-alibaba-jmanus/README.md, spring-ai-alibaba-jmanus/pom.xml, spring-ai-alibaba-jmanus/script/build_embedded_jdk.sh, spring-ai-alibaba-jmanus/script/create_dmg.sh, spring-ai-alibaba-jmanus/script/create_dmg_embedded.sh, spring-ai-alibaba-jmanus/script/start_jmanus.sh
- build macos dmg
- build and push dockerhub image
=> feat(jmanus): support build macos and docker image

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/advisor/DashScopeDocumentAnalysisAdvisor.java
=> refactor(core): 优化文档分析顾问的提示模板，提高文档解析的稳定性

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/CompiledGraph.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/SubGraphTest.java
#1400
CompiledGraph 目前嵌套2层以上子图会报错，修改ProcessedNodesEdgesAndConfig递归process以支持多层嵌套子图
=> fix(graph): 递归process以支持多层嵌套子图

spring-ai-alibaba-jmanus/ui-vue3/src/base/i18n/en.ts, spring-ai-alibaba-jmanus/ui-vue3/src/base/i18n/zh.ts, spring-ai-alibaba-jmanus/ui-vue3/src/components/blurCard/index.vue, spring-ai-alibaba-jmanus/ui-vue3/src/views/home/index.vue
1. Implemented:
- Added direct page navigation button
- Introduced plan-act mode card components
2. Fixed:
- Resolved miscellaneous component defects
#1515 
1. Implemented card categorization with two types: message and plan.
2. Added functionality to trigger sidebar for saving and executing plans when navigating from plan cards.
=> feat(jmanus): added a button to navigate to the direct page, incorporated plan-act mode cards, and fixed several component issues.

spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/service/simple/SimpleVectorStoreService.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/test/java/com/alibaba/cloud/ai/service/simple/SimpleVectorStoreServiceTest.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-common/src/main/java/com/alibaba/cloud/ai/dbconnector/DbAccessor.java
=> test(nl2sql): simplevectorstoreservice test add

spring-ai-alibaba-jmanus/src/main/resources/prompts/startup-agents/default_agent/agent-config.yml
=> fix(jmanus): remove bash usage in default agent by default

spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/mcp/model/vo/McpTool.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/planning/PlanningFactory.java
=> feat(jmanus): support smart context compress for mcp tools

spring-ai-alibaba-studio/ui/.env.development, spring-ai-alibaba-studio/ui/.env.production
The should not be committed 应为 The file should not be committed
=> chore(studio): fix typos

spring-ai-alibaba-jmanus/README.md
update readme.md and update images containing Chinese text.
NONE
=> feat(jmanus): update readme.md

spring-ai-alibaba-jmanus/ui-vue3/src/components/cron-task-modal/TaskDetailModal.vue, spring-ai-alibaba-jmanus/ui-vue3/src/components/cron-task-modal/index.vue
Fixed warnings related to the nullish coalescing (??) operators in front-end scheduled tasks.
NONE
=> fix(jmanus): fixed warnings related to front-end scheduled tasks.

community/tool-calls/spring-ai-alibaba-starter-tool-calling-googlescholar/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-googlescholar/src/main/java/com/alibaba/cloud/ai/toolcalling/googlescholar/GoogleScholarAutoConfiguration.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-googlescholar/src/main/java/com/alibaba/cloud/ai/toolcalling/googlescholar/GoogleScholarConstants.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-googlescholar/src/main/java/com/alibaba/cloud/ai/toolcalling/googlescholar/GoogleScholarProperties.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-googlescholar/src/main/java/com/alibaba/cloud/ai/toolcalling/googlescholar/GoogleScholarService.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-googlescholar/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, community/tool-calls/spring-ai-alibaba-starter-tool-calling-googlescholar/src/test/java/com/alibaba/cloud/ai/toolcalling/googlescholar/GoogleScholarTest.java, pom.xml, spring-ai-alibaba-bom/pom.xml
在`application.yml`或`application.properties`中配置：
```yaml
spring:
ai:
alibaba:
toolcalling:
googlescholar:
enabled: true                 # 是否启用，默认true
num-results: 10               # 返回结果数量，默认10，最大20
language: en                  # 搜索语言，默认en
include-citations: true       # 是否包含引用次数，默认true
timeout: 30000               # 请求超时时间（毫秒），默认30000
```
=> feat(tool-calls): add Google Scholar search tool

spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/ResearcherNode.java
=> fix(deepresearch): error get of site_info

spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/llm/LlmService.java
修复openai配置不支持自定义completionsPath和embeddingsPath配置问题
修复问题：https://github.com/alibaba/spring-ai-alibaba/issues/1801
将配置写死部分改为动态从配置文件获取
=> fix(jmanus):  fix the issue where openai configuration does not support custom perfectionsPath and embeddingsPath configurations

community/tool-calls/spring-ai-alibaba-starter-tool-calling-metaso/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-metaso/src/main/java/com/alibaba/cloud/ai/toolcalling/metaso/MetasoAutoConfiguration.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-metaso/src/main/java/com/alibaba/cloud/ai/toolcalling/metaso/MetasoConstants.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-metaso/src/main/java/com/alibaba/cloud/ai/toolcalling/metaso/MetasoProperties.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-metaso/src/main/java/com/alibaba/cloud/ai/toolcalling/metaso/MetasoService.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-metaso/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, community/tool-calls/spring-ai-alibaba-starter-tool-calling-metaso/src/test/java/com/alibaba/cloud/ai/toolcalling/metaso/MetasoServiceTest.java, community/tool-calls/spring-ai-alibaba-starter-tool-calling-searches/pom.xml, community/tool-calls/spring-ai-alibaba-starter-tool-calling-searches/src/main/java/com/alibaba/cloud/ai/toolcalling/searches/SearchEnum.java, pom.xml, spring-ai-alibaba-bom/pom.xml
添加 秘塔AI 搜索工具
秘塔算是国内目前比较火的ai搜索工具，可以考虑加入到tools中
NONE
- 新增 MetasoAutoConfiguration、MetasoConstants、MetasoProperties、MetasoService 等类
- 集成进SearchUtil中
- 添加了单元测试用例
- 更新了相关的 pom.xml 文件
=> feat(tool-calls): add metaso search tool

spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/CoderNode.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/ParallelExecutorNode.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/ResearchTeamNode.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/ResearcherNode.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/util/StateUtil.java
LLM calling fails and other exceptions in researcherNode / CoderNode will cause infinite waiting. This PR add basic error handling mechanism.
Add error status and exit when error.
Test with exceptions throwing.
=> fix(deepresearch): enable researchTeam error handling mechanism

.github/workflows/greeting-guideline-pr.yml, spring-ai-alibaba-graph/spring-ai-alibaba-graph-example/README.md
fix(graph): update readme.md typo
=> fix(graph): update readme.md typo

spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-management/src/main/resources/application.yml
=> chore(nl2sql): improve yml

spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/model/entity/DynamicModelEntity.java
=> fix(jmanus): fix many to many exception

spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/DynamicAgent.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/event/PlanExceptionEvent.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/exception/PlanException.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/exception/handler/GlobalExceptionHandler.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/llm/StreamingResponseHandler.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/planning/controller/ManusController.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/planning/creator/PlanCreator.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/planning/finalizer/PlanFinalizer.java, spring-ai-alibaba-jmanus/ui-vue3/src/api/common-api-service.ts, spring-ai-alibaba-jmanus/ui-vue3/src/components/chat/index.vue, spring-ai-alibaba-jmanus/ui-vue3/src/utils/plan-execution-manager.ts, spring-ai-alibaba-jmanus/ui-vue3/src/views/direct/index.vue
支持后端错误在聊天框展示和全局异常处理，对应这个feature：https://github.com/alibaba/spring-ai-alibaba/issues/1840
添加了全局异常处理，以及前端页面的优化和信息展示
=> feat(jmanus): support backend error display in chat boxes and global exception handling

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/node/code/javascript/NodeJsTemplateTransformer.java
=> chore(core): update comment

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/node/KnowledgeRetrievalNode.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/model/workflow/nodedata/KnowledgeRetrievalNodeData.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/service/dsl/nodes/KnowledgeRetrievalNodeDataConverter.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/service/generator/workflow/WorkflowProjectGenerator.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/service/generator/workflow/sections/KnowledgeRetrievalNodeSection.java
Resolve Transform Dify's DSL mapping fields do not match KnowledgeRetrievalNode
fix #1647
=> feat(graph): refine KnowledgeRetrievalNode for graph studio

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/action/AsyncNodeAction.java
=> fix(graph): improve async node action

spring-ai-alibaba-jmanus/build-ui.bat
=> feat(jmanus): add windows build vue filev

spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/advisor/DocumentRetrievalAdvisorTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/chat/observation/DashScopeChatModelObservationConventionTests.java
=> chore(core): translate comments

spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/service/generator/workflow/sections/AnswerNodeSection.java
=> fix(graph): answerNodeSection

spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/config/CodeExecutorConfiguration.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/config/CodeExecutorProperties.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-management/src/main/resources/application.yml
=> fix(nl2sql): remove 'enabled' filed in CodeExecutorProperties

spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/config/RedirectController.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/config/startUp/AppStartupListener.java
优化首页路径问题，解决问题：https://github.com/alibaba/spring-ai-alibaba/issues/1917
添加根路径转发
=> fix(jmanus): add root path forwarding to solve the problem of Docker root path being inaccessible

spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/config/Nl2sqlConfiguration.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/constant/Constant.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/dto/BusinessKnowledgeDTO.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/dto/SemanticModelDTO.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/node/TableRelationNode.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/service/semantic/SemanticModelRecallService.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-management/src/main/java/com/alibaba/cloud/ai/controller/Nl2sqlForGraphController.java
fix the error param of semanticModelRecallService
fix the sql of semanticModelRecallService
sync semanticModelDTO businessKnowledgeDTO 
add new QueryParam "agentId" to the interface of nl2sql/search
=> fix(nl2sql): fix the error param of semanticModelRecallService

spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/model/workflow/nodedata/ToolNodeData.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/service/dsl/nodes/ToolNodeDataConverter.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/test/java/com/alibaba/cloud/ai/dsl/adapters/DifyDSLAdapterTest.java
…tribute correspondence problem #1897
Enhance the nodes called by tools in graph and fix the attribute correspondence problem
=> fix(graph): enhance the nodes called by tools in graph #1897

spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-web-ui/src/components/AgentDebugPanel.vue, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-web-ui/src/views/AgentDetail.vue
=> feat(nl2sql): separate debug and release mode

auto-configurations/spring-ai-alibaba-autoconfigure-mcp-gateway-core/pom.xml, pom.xml, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-gateway/spring-ai-alibaba-mcp-gateway-core/pom.xml
…dency
evert mcp.version to 0.10.0
=> fix(mcp): revert mcp.version to 0.10.0 

spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/node/SqlExecuteNode.java
=> fix(nl2sql): unify status response creation for display messages

spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/planning/finalizer/PlanFinalizer.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/cron/CronTool.java
=> fix(jmanus): Fix the scheduled task bug caused by internationalization

spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/main/java/com/alibaba/cloud/ai/service/dsl/adapters/DifyDSLAdapter.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/src/test/java/com/alibaba/cloud/ai/dsl/adapters/DifyDSLAdapterTest.java
Correctly handle the IllegalArgumentException problem of variable values in Dify DSL
Closes #2066
Correctly handle the IllegalArgumentException problem of variable values in Dify DSL
=> fix(graph): problem of variable values in Dify DSL

spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-web-ui/package.json
=> feat(nl2sql): enable host option for development script

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/CompileConfig.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/CompiledGraph.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/HasMetadata.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/RunnableConfig.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/internal/node/ParallelNode.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/streaming/StreamingChatGenerator.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/InterruptionTest.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/StateGraphTest.java
add support for interruption before edge evaulation
NONE
see com.alibaba.cloud.ai.graph.InterruptionTest
see com.alibaba.cloud.ai.graph.StateGraphTest#testRunnableInterrupt
see com.alibaba.cloud.ai.graph.InterruptionTest
see com.alibaba.cloud.ai.graph.StateGraphTest#testRunnableInterrupt
=> feat(graph): add support for interruption before edge evaulation

spring-ai-alibaba-nl2sql/README.md
=> fix(nl2sql): update image references in README.md

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/advisor/CompositeDocumentRetriever.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/advisor/DocumentRetrievalAdvisor.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/advisor/CompositeDocumentRetrieverTests.java
it support searching multiple databases at the same time from 1803
Close  #1803
=> feat(core): support searching multiple VectorStore

auto-configurations/spring-ai-alibaba-autoconfigure-mcp-router/src/main/java/com/alibaba/cloud/ai/autoconfigure/mcp/gateway/core/McpGatewayServerAutoConfiguration.java, auto-configurations/spring-ai-alibaba-autoconfigure-mcp-router/src/main/java/com/alibaba/cloud/ai/autoconfigure/mcp/gateway/nacos/NacosMcpGatewayAutoConfiguration.java, auto-configurations/spring-ai-alibaba-autoconfigure-mcp-router/src/main/java/com/alibaba/cloud/ai/autoconfigure/mcp/router/NacosMcpRouterAutoConfiguration.java
=> feat(mcp): mcp router switch

spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/controller/ChatController.java
=> fix(deepresearch): send error response to the page

spring-ai-alibaba-deepresearch/pom.xml, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/config/SmartAgentProperties.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/controller/ChatController.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/CompileConfig.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/StateGraph.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/checkpoint/config/SaverConfig.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/checkpoint/constant/SaverEnum.java, spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/InterruptionTest.java, spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/StateGraphFileSystemSaverTest.java, spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/StateGraphMemorySaverTest.java, spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/SubGraphTest.java, spring-ai-alibaba-studio/spring-ai-alibaba-studio-client/src/main/java/com/alibaba/cloud/ai/service/impl/GraphServiceImpl.java
=> feat(graph): saver adjust enum

spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-router/src/main/java/com/alibaba/cloud/ai/mcp/router/model/response/McpDebugResponse.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-router/src/main/java/com/alibaba/cloud/ai/mcp/router/model/response/McpServerAddResponse.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-router/src/main/java/com/alibaba/cloud/ai/mcp/router/model/response/McpServerSearchResponse.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-router/src/main/java/com/alibaba/cloud/ai/mcp/router/model/response/McpToolExecutionResponse.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-router/src/main/java/com/alibaba/cloud/ai/mcp/router/service/McpRouterService.java
add MCP router service debugging and response models
=> feat(mcp): add MCP router service debugging and response models

spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/OverAllState.java, spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/DefaultKeyStrategyTest.java, spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/OverAllStateBuilderTest.java
implement default key strategy for state updates
=> feat(graph): implement default key strategy for state updates

spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/agents/McpAssignNodeConfiguration.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/BackgroundInvestigationNode.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/CoordinatorNode.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/ProfessionalKbDecisionNode.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/RagNode.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/ReporterNode.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/RewriteAndMultiQueryNode.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/util/StateUtil.java
=> feat(deepresearch): optimize

spring-ai-alibaba-deepresearch/Dockerfile
=> feat(deepresearch): update Dockerfile

spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/node/code/DockerCodeExecutorTest.java
Run the testPython3Sum only in CI env.
=> fix(graph): Run the testPython3Sum only in CI env.

spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/agent/ReactAgent.java, spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/agent/ReactAgentHookTest.java
llmInputMessagesKey  -> inputKey
=> feat(graph): reactagent with inputkey

spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-web-ui/src/components/AgentDebugPanel.vue
=> feat(nl2sql): reset debug query to empty when starting debug

.mvn/mvnd.properties, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/checkpoint/savers/FileSystemSaver.java, spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/checkpoint/FileSystemSaverDeleteFileTest.java
* Uses the NIO API to check the existence and type of the target directory. If the directory is missing, it will be automatically created to ensure the directory structure is correct.
* Utilizes `Files.deleteIfExists` to delete checkpoint files and logs failures when deletion fails, improving operation reliability.
* Adds new unit tests to validate deletion behavior for scenarios where files exist or do not exist.
NONE
* Replaced legacy file checking with the NIO API for more reliable existence and type validation.
* Used `Files.deleteIfExists` for safe deletion and added error logging when deletion fails.
* Added unit tests to verify both successful and unsuccessful deletion scenarios.
```bash
./mvnw -q -pl spring-ai-alibaba-graph-core test
mvn -q -pl spring-ai-alibaba-graph-core test -o …
```
=> refactor(graph): enhance FileSystemSaver initialization and deletion

spring-ai-alibaba-graph-core/pom.xml, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/CompileConfig.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/CompiledGraph.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/OverAllState.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/OverAllStateBuilder.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/store/NamespaceListRequest.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/store/Store.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/store/StoreItem.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/store/StoreSearchRequest.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/store/StoreSearchResult.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/store/constant/StoreConstant.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/store/stores/BaseStore.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/store/stores/DatabaseStore.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/store/stores/FileSystemStore.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/store/stores/MemoryStore.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/store/stores/MongoStore.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/store/stores/RedisStore.java, spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/store/GraphStoreIntegrationTest.java, spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/store/StoreIntegrationTest.java, spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/store/stores/DatabaseStoreTest.java, spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/store/stores/FileSystemStoreTest.java, spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/store/stores/MemoryStoreTest.java, spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/store/stores/MongoStoreTest.java, spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/store/stores/RedisStoreTest.java
=> feat(graph): support Store

spring-ai-alibaba-graph-core/pom.xml, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/agent/a2a/A2aNode.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/agent/a2a/A2aRemoteAgent.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/agent/a2a/RemoteAgentCard.java, spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/agent/RemoteAgentTest.java
- **Related Issue**: None
- **Module Path**: spring-ai-alibaba-graph-core
- **Core Changes**: Added A2A protocol client component, supporting consistent Agent creation method with regular Agents, automatically parsing AgentCard URL and loading configurations
- **Submitter**: xiaorenwu234
- **Submission Date**: August 25, 2025
In the existing spring-ai-alibaba-graph-core module, Agents all use in-process multi-Agent interaction. To meet the requirements of remote multi-Agent scenarios and adapt to cross-service Agent calling scenarios using A2A (Agent-to-Agent) protocol, this development adds A2A protocol Client with the following core goals:
1. Maintain consistency in Agent creation process, allowing developers to use A2A protocol Agents without learning new APIs
2. Support automatic …
=> feat(core): add A2A Remote Agent Client

spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/controller/ChatController.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/controller/RagDataController.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/controller/graph/GraphProcess.java, spring-ai-alibaba-deepresearch/ui-vue3/package.json, spring-ai-alibaba-deepresearch/ui-vue3/src/store/MessageStore.ts, spring-ai-alibaba-deepresearch/ui-vue3/src/types/base.ts, spring-ai-alibaba-deepresearch/ui-vue3/src/types/message.ts, spring-ai-alibaba-deepresearch/ui-vue3/src/types/node.ts, spring-ai-alibaba-deepresearch/ui-vue3/src/types/upload.ts, spring-ai-alibaba-deepresearch/ui-vue3/src/utils/request.ts, spring-ai-alibaba-deepresearch/ui-vue3/src/views/chat/index.vue
1. support current session add rag file upload
2. support current session stop action
NONE
=> feat(deepresearch): add chat rag file upload and add stop action

spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/CompiledGraph.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/internal/node/ParallelNode.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/streaming/StreamingChatGenerator.java, spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/StateGraphStreamTest.java, spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/stream/LLmNodeAction.java
enhance parallel model
NONE
see com.alibaba.cloud.ai.graph.internal.node.ParallelNode
see com.alibaba.cloud.ai.graph.StateGraphStreamTest#testParallelNodeStream
=> feat(graph): enhance parallel model

spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/StateGraphFileSystemSaverTest.java
=> fix(graph): fix graph ci

spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/checkpoint/Checkpoint.java, spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/StateGraphStreamTest.java
add JSON annotations to Checkpoint constructor
=> fix(graph): add JSON annotations to Checkpoint constructor

.github/workflows/lint-pr-title.yml, auto-configurations/spring-ai-alibaba-autoconfigure-a2a-server/pom.xml, auto-configurations/spring-ai-alibaba-autoconfigure-a2a-server/src/main/java/com/alibaba/cloud/ai/autoconfigure/a2a/server/A2aAgentCardAutoConfiguration.java, auto-configurations/spring-ai-alibaba-autoconfigure-a2a-server/src/main/java/com/alibaba/cloud/ai/autoconfigure/a2a/server/A2aServerAutoConfiguration.java, auto-configurations/spring-ai-alibaba-autoconfigure-a2a-server/src/main/java/com/alibaba/cloud/ai/autoconfigure/a2a/server/A2aServerHandlerAutoConfiguration.java, auto-configurations/spring-ai-alibaba-autoconfigure-a2a-server/src/main/resources/META-INF/additional-spring-configuration-metadata.json, auto-configurations/spring-ai-alibaba-autoconfigure-a2a-server/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, pom.xml, spring-ai-alibaba-a2a/pom.xml, spring-ai-alibaba-a2a/spring-ai-alibaba-a2a-common/pom.xml, spring-ai-alibaba-a2a/spring-ai-alibaba-a2a-common/src/main/java/com/alibaba/cloud/ai/a2a/A2aServerProperties.java, spring-ai-alibaba-a2a/spring-ai-alibaba-a2a-common/src/main/java/com/alibaba/cloud/ai/a2a/registry/AgentRegistry.java, spring-ai-alibaba-a2a/spring-ai-alibaba-a2a-common/src/main/java/com/alibaba/cloud/ai/a2a/registry/AgentRegistryService.java, spring-ai-alibaba-a2a/spring-ai-alibaba-a2a-common/src/main/java/com/alibaba/cloud/ai/a2a/route/A2aRouterProvider.java, spring-ai-alibaba-a2a/spring-ai-alibaba-a2a-common/src/main/java/com/alibaba/cloud/ai/a2a/route/JsonRpcA2aRouterProvider.java, spring-ai-alibaba-a2a/spring-ai-alibaba-a2a-common/src/main/java/com/alibaba/cloud/ai/a2a/server/A2aRequestHandler.java, spring-ai-alibaba-a2a/spring-ai-alibaba-a2a-common/src/main/java/com/alibaba/cloud/ai/a2a/server/A2aServerExecutorProvider.java, spring-ai-alibaba-a2a/spring-ai-alibaba-a2a-common/src/main/java/com/alibaba/cloud/ai/a2a/server/DefaultA2aServerExecutorProvider.java, spring-ai-alibaba-a2a/spring-ai-alibaba-a2a-common/src/main/java/com/alibaba/cloud/ai/a2a/server/GraphAgentExecutor.java, spring-ai-alibaba-a2a/spring-ai-alibaba-a2a-common/src/main/java/com/alibaba/cloud/ai/a2a/server/JsonRpcA2aRequestHandler.java, spring-ai-alibaba-a2a/spring-ai-alibaba-a2a-common/src/main/java/com/alibaba/cloud/ai/a2a/server/ServerTypeEnum.java, spring-ai-alibaba-a2a/spring-ai-alibaba-a2a-common/src/main/java/com/alibaba/cloud/ai/a2a/utils/InetUtils.java, spring-ai-alibaba-graph-core/pom.xml, spring-ai-alibaba-spring-boot-starters/spring-ai-alibaba-starter-a2a-server/pom.xml
support start a2a agent server by simple starter.
For #2303
=> feat(a2a): support a2a server starter.

spring-ai-alibaba-studio/spring-ai-alibaba-studio-client/pom.xml
studio-client application can't run because of  log dependency conflict. 
I exclude the jboss logging jar.
the application can run now .
=> fix(studio): fix the dependency conflict

README.md
Fixed typo in phrase multi-gent to multi-agent.
Fixed a typo in readme.md
=> fix(docs): update readme.md typo

spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/service/base/BaseNl2SqlService.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/service/base/BaseSchemaService.java
优化 agentId 空值检查
NONE
- 在 BaseNl2SqlService 和 BaseSchemaService 中
- 添加对 agentId 进行 trim 并检查是否为空的逻辑
- 避免因空的 agentId 导致的潜在错误或异常
=> fix(nl2sql): 优化 agentId 空值检查

spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/config/Nl2sqlConfiguration.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/constant/Constant.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/dispatcher/TableRelationDispatcher.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/node/TableRelationNode.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/test/java/com/alibaba/cloud/ai/dispatcher/TableRelationDispatcherTest.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/test/java/com/alibaba/cloud/ai/node/TableRelationNodeTest.java
TableRelationNode  在发生调数据库异常的时候会无限循环不断重试。
Fixes #2341
1、在TableRelationNode   节点之后增加条件边，根据异常消息和最大重试次数决定是否可重试。
2、补充了TableRelationNode  的单元测试
3、补充了TableRelationDispatcher的单元测试
=> fix(nl2sql): fix nl2sql TableRelationNode infinite loop(#2341)

spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-registry/src/main/java/com/alibaba/cloud/ai/mcp/discovery/client/transport/LoadbalancedMcpAsyncClient.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-registry/src/main/java/com/alibaba/cloud/ai/mcp/discovery/client/transport/LoadbalancedMcpSyncClient.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-registry/src/main/java/com/alibaba/cloud/ai/mcp/register/NacosMcpRegister.java
=> fix(mcp): 完善 MCP 相关的日志

spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/util/StreamingChatGeneratorUtil.java
adapt graph flux stream to resolve the issue of the graph not being able to run in a streaming manner
fix #2406
=> fix(nl2sql): adapt graph flux stream

spring-ai-alibaba-a2a/spring-ai-alibaba-a2a-common/src/main/java/com/alibaba/cloud/ai/a2a/route/JsonRpcA2aRouterProvider.java
- Fix A2a Server don't send end event.
=> fix(a2a): a2a server don't send end event.

spring-ai-alibaba-nl2sql/docker-file/Dockerfile-backend, spring-ai-alibaba-nl2sql/docker-file/docker-compose.yml
=> fix(nl2sql): fix docker file

spring-ai-alibaba-a2a/spring-ai-alibaba-a2a-common/src/main/java/com/alibaba/cloud/ai/a2a/server/GraphAgentExecutor.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/agent/BaseAgent.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/agent/a2a/A2aNodeWithConfig.java
=> fix(a2a): a2a session pass-through

spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/executor/NodeExecutor.java
=> fix: result empty

spring-ai-alibaba-studio/spring-ai-alibaba-studio-server/spring-ai-alibaba-studio-server-admin/src/main/java/com/alibaba/cloud/ai/studio/admin/generator/format/EclipseJdtFormatProjectContributor.java, spring-ai-alibaba-studio/spring-ai-alibaba-studio-server/spring-ai-alibaba-studio-server-admin/src/main/java/com/alibaba/cloud/ai/studio/admin/generator/service/generator/agent/impl/LlmRoutingAgentProvider.java, spring-ai-alibaba-studio/spring-ai-alibaba-studio-server/spring-ai-alibaba-studio-server-admin/src/main/java/com/alibaba/cloud/ai/studio/admin/generator/service/generator/agent/impl/LoopAgentProvider.java, spring-ai-alibaba-studio/spring-ai-alibaba-studio-server/spring-ai-alibaba-studio-server-admin/src/main/java/com/alibaba/cloud/ai/studio/admin/generator/service/generator/agent/impl/ParallelAgentProvider.java, spring-ai-alibaba-studio/spring-ai-alibaba-studio-server/spring-ai-alibaba-studio-server-admin/src/main/java/com/alibaba/cloud/ai/studio/admin/generator/utils/CodeGenUtils.java
add add llm\loop\parallel agent provider, provided the initial version of an agent schema transformation
NONE
=> feat(graph): add llm\loop\parallel agent provider

pom.xml
- Upgrade nacos client from `3.1.0-BETA` to `3.1.0`.
NONE
=> infra(core): upgrade nacos client version to 3.1.0.

spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-management/src/main/java/com/alibaba/cloud/ai/mapper/AgentKnowledgeMapper.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-management/src/main/java/com/alibaba/cloud/ai/mapper/AgentMapper.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-management/src/main/java/com/alibaba/cloud/ai/mapper/AgentPresetQuestionMapper.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-management/src/main/java/com/alibaba/cloud/ai/service/AgentKnowledgeService.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-management/src/main/java/com/alibaba/cloud/ai/service/AgentPresetQuestionService.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-management/src/main/java/com/alibaba/cloud/ai/service/AgentService.java
=> fix(nl2sql): change jdbctemplate to mybatis in services

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatModel.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatOptions.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatOptionsTests.java
=> feat(core): add  thinking_budget 

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/video/DashScopeVideoModel.java
=> feat(core): fix video retry

spring-ai-alibaba-agent-nacos/src/main/java/com/alibaba/cloud/ai/agent/nacos/NacosAgentPromptBuilder.java, spring-ai-alibaba-agent-nacos/src/main/java/com/alibaba/cloud/ai/agent/nacos/NacosOptions.java, spring-ai-alibaba-agent-nacos/src/main/java/com/alibaba/cloud/ai/agent/nacos/NacosPartnerAgentsInjector.java, spring-ai-alibaba-agent-nacos/src/main/java/com/alibaba/cloud/ai/agent/nacos/NacosReactAgentBuilder.java, spring-ai-alibaba-agent-nacos/src/main/java/com/alibaba/cloud/ai/agent/nacos/ObservationConfiguration.java, spring-ai-alibaba-agent-nacos/src/main/java/com/alibaba/cloud/ai/agent/nacos/config/NacosAgentConfig.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/video/DashScopeVideoOptions.java
=> chore(core): fix typos

pom.xml, spring-ai-alibaba-graph-core/pom.xml, spring-ai-alibaba-studio/spring-ai-alibaba-studio-client/pom.xml
1. add maven depency
```
<dependency>
<groupId>io.modelcontextprotocol.sdk</groupId>
<artifactId>mcp-bom</artifactId>
<version>${mcp.version}</version>
<type>pom</type>
<scope>import</scope>
</dependency>
```
2. update mcp.version's version to 0.11.2 defined in module `spring-ai-alibaba-studio/spring-ai-alibaba-studio-client/pom.xml`
=> perf(mcp): add maven dependency `mcp-bom`
