alibaba/spring-ai-alibaba

spring-ai-alibaba-examples/playground-flight-booking/src/main/resources/application.properties
**Fix for Incorrect Configuration Description**
This PR addresses an error in the configuration file where the dashscope settings were mistakenly placed under the openai section. We have now relocated it to the correct position to ensure the accuracy and clarity of the configuration file.
**Changes Made**
Corrected the description for dashscope in the configuration file
Ensured all related documentation and comments are consistent with the new configuration
Thank you for reviewing! Please let me know if any further adjustments are needed.
=> fix:add dashscope config desc

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/DashScopeAiStreamFunctionCallingHelper.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/DashScopeApi.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/chat/client/DashScopeChatClientIT.java
using cmd: mvn io.spring.javaformat:spring-javaformat-maven-plugin:0.0.39:apply
=> format: fix formatting violations

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/autoconfigure/dashscope/DashScopeAutoConfiguration.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/DashscopeAiTestConfiguration.java, spring-ai-alibaba-examples/playground-flight-booking/pom.xml
1. fix the assertion that audioApi is null when constructing DashScopeAudioSpeechModelOpenAPI
2. fix typos
=> fix chat mode unit test

pom.xml, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/advisor/DocumentRetrievalAdvisor.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/advisor/RetrievalRerankAdvisor.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/autoconfigure/dashscope/DashScopeChatProperties.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/agent/DashScopeAgentOptions.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/DashScopeApi.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatModel.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatOptions.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/rag/DashScopeDocumentRetrievalAdvisor.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/evaluation/LaajEvaluator.java
Update Spring AI dependency to 1.0.0-M3 and refactor the expired implementations of some components.
NONE
1. Update dependency in pom.xml.
2. Replace the implementation interfaces of `DocumentRetrievalAdvisor`, `RetrievalRerankAdvisor`, and `DashScopeDocumentRetrievalAdvisor` with `CallAroundAdvisor` and `StreamAroundAdvisor` to substitute the deprecated `RequestResponseAdvisor`.
3. Replace the `Float` fields in `ModelOptions` with `Double`, according to [related issue](https://github.com/spring-projects/spring-ai/issues/712).
=> feat: update Spring AI dependency to 1.0.0-M3

spring-ai-alibaba-core/pom.xml, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatModel.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatOptions.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/observation/DashScopeChatModelObservationConvention.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/observation/package-info.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/observation/conventions/AiProvider.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/DashscopeAiTestConfiguration.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatModelObservationIT.java
Add DashScopeChatModel call and stream observability so that we can trace and generate metrics for `DashScopeChatModel`.
=> feat: add DashScopeChatModel call and stream observability

community/document-readers/yuque-reader/pom.xml, community/document-readers/yuque-reader/src/main/java/com/alibaba/cloud/ai/reader/yuque/YuQueDocumentReader.java, community/document-readers/yuque-reader/src/main/java/com/alibaba/cloud/ai/reader/yuque/YuQueResource.java, community/document-readers/yuque-reader/src/test/java/com/alibaba/cloud/ai/reader/yuque/YuQueDocumentLoaderIT.java
add yuquedoc reader 
#98 
insert token and url then run test class
=> Feature:add yuque reader

spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/components/Nodes/Common/manageNodes.tsx, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/components/Nodes/StartNode/index.tsx, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/pages/Graph/Design/map.tsx
- Implements the foundational layout for a context menu.
- Adds functionality to create a new node via the right-click menu.
🛠️ Implement the ability to create a new node on the workflow graph.
NONE
⭐️ The code commited is brief, so just check it directly.
🎥 The video below shows how it works: 
https://github.com/user-attachments/assets/e9bb53f4-6e7a-4731-b221-8295635bc48f
=> feat(front-end): Add basic structure for right-click menu and new node creation

spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/package.json, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/pnpm-lock.yaml, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/components/Nodes/Common/manageNodes.tsx, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/components/Nodes/LLMNode/index.tsx, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/components/Nodes/StartNode/index.tsx, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/pages/Graph/Design/map.tsx, spring-ai-alibaba-graph/spring-ai-alibaba-graph-studio/graph-ui/src/pages/Graph/Design/types.ts
Implement copy and paste functionality for nodes with using the right-click menu.
NONE
**Copy**
- Convert the node's data structure to a standardized DSL schema.
- Store the DSL schema in the clipboard.
**Paste**
- Retrieve the DSL schema from the clipboard.
- Convert the DSL schema back into the original data structure.
1. Select a node within the graph.
2. Right-click on the selected node to open the context menu.
3. Choose the "Copy" option from the menu.
4. Right-click again in an empty area of the graph and select "Paste" from the context menu.
=> feat(front-end): Implement the feature of copy and paste of the menu

spring-ai-alibaba-core/pom.xml, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/rag/OpenSearchConfig.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/rag/OpenSearchVector.java
Describe what this PR does / why we need it
Add implementation and configuration classes for OpenSearch vector storage
Does this pull request fix one issue?
yes,https://github.com/alibaba/spring-ai-alibaba/issues/230
Describe how you did it
- Added OpenSearchVector.java file, which implements the VectorStore interface for interacting with Alibaba OpenSearch. This class supports functionalities such as adding, deleting, and similarity searching of vector documents.
- Added OpenSearchConfig.java file, which defines the parameters required to connect and configure OpenSearch, including instance ID, endpoint, username, and password.
Describe how to verify it
Special notes for reviews
=> feat: Add implementation and configuration classes for OpenSearch vector storage

community/document-readers/mysql-document-reader/README.md, community/document-readers/mysql-document-reader/pom.xml, community/document-readers/mysql-document-reader/src/main/java/com/alibaba/cloud/ai/reader/mysql/MySQLDocumentReader.java, community/document-readers/mysql-document-reader/src/main/java/com/alibaba/cloud/ai/reader/mysql/MySQLResource.java, community/document-readers/mysql-document-reader/src/test/java/com/alibaba/cloud/ai/reader/mysql/MySQLDocumentReaderTest.java, pom.xml
实现了基于Spring AI的MySQL文档读取器，支持从MySQL数据库读取数据并转换为文档格式。
Implemented a MySQL document reader based on Spring AI, supporting reading data from MySQL database and converting it to document format.
- 使用纯JDBC实现，无需额外依赖
Pure JDBC implementation, no additional dependencies required
- 支持自定义内容列和元数据列
Support for custom content and metadata columns
- 完善的错误处理和资源自动关闭
Comprehensive error handling and automatic resource cleanup
- 支持自定义SQL查询
Support for custom SQL queries
- 使用JDBC直接连接MySQL数据库
Using JDBC to connect MySQL database directly
- 支持灵活的字段映射配置
Supporting flexible field mapping configuration
- 实现了自动资源管理和异常处理
Implemented automatic resource management and exception handling
- 提供了完整的单元测试
Provided comprehensive unit tests
- 基本功能测试：文档读取和转换
Basic functionality tests: document reading and conversion
- …
=> feat(document-readers): add mysql implements

community/document-parsers/document-parser-bshtml/pom.xml, community/document-readers/mbox-document-reader/README.md, community/document-readers/mbox-document-reader/pom.xml, community/document-readers/mbox-document-reader/src/main/java/com/alibaba/cloud/ai/reader/mbox/MboxDocumentReader.java, community/document-readers/mbox-document-reader/src/test/java/com/alibaba/cloud/ai/reader/mbox/MboxDocumentReaderTest.java, community/document-readers/mbox-document-reader/src/test/resources/invalid.mbox, community/document-readers/mbox-document-reader/src/test/resources/sample.mbox, pom.xml
This PR adds a new document reader implementation for Mbox format emails, which enables Spring AI to process email data from Mbox files. This is useful for scenarios where we need to analyze or process email content in batch.
此 PR 添加了一个新的 Mbox 格式邮件文档读取器实现，使 Spring AI 能够处理 Mbox 文件中的邮件数据。这对于需要批量分析或处理邮件内容的场景非常有用。
NONE
- Implemented MboxDocumentReader using Apache Commons IO for file reading
- Used JSoup for HTML content parsing
- Added support for different email formats (plain text, HTML, multipart)
- Implemented robust error handling with runtime exceptions
- Added comprehensive test cases with sample mbox files
- Created bilingual documentation
- 使用 Apache Commons IO 实现 MboxDocumentReader 的文件读取
- 使用 JSoup 进行 HTML 内容解析
- 添加对不同邮件格式的支持（纯文本、HTML、多部分）
- 实现使用运行时异常的健壮错误处理
- 使用示例 mbox 文件添加全面的测试用例 …
=> feat(document-readers): add mbox implements  ( License cannot be added to an mbox file.)

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/pom.xml, spring-ai-alibaba-studio/pom.xml, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/api/GraphAPI.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/config/GraphAutoConfiguration.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/controller/GraphAPIController.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/function/AgentFunctionCallbackWrapper.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/graph/AiInsurance.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/graph/HumanNode.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/graph/InitData.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/graph/InitDataSerializer.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/graph/IsAgentService.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/graph/NodeOutputSerializer.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/graph/PersistentConfig.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/graph/PromptNode.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/graph/ToolService.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/param/GraphStreamParam.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/service/GraphService.java, spring-ai-alibaba-studio/src/main/java/com/alibaba/cloud/ai/service/impl/GraphServiceImpl.java
Merge graph-run module into studio
1. startup CliDebugExampleApplication
2. execute in your terminal: 
> curl 'http://localhost:8080/studio/api/graph/stream?thread=default' \
-H 'Accept: */*' \
-H 'Accept-Language: zh-CN,zh;q=0.9' \
-H 'Cache-Control: no-cache' \
-H 'Connection: keep-alive' \
-H 'Content-Type: application/json' \
-H 'Cookie: JSESSIONID=node01fouu9prlcx8u1xfmam4zzynpy0.node0' \
--data-raw '{"input":""}' -v
3. execute in your another terminal in order: 
> curl -X POST 'http://localhost:8080/studio/api/graph/user/input' -H 'Content-Type: application/json' --data '{"input":"年龄21 性别男 学历本科"}'
> curl -X POST 'http://localhost:8080/studio/api/graph/user/input' -H 'Content-Type: application/json' --data '{"input":"我要买保险"}'
> curl -X POST …
=> Merge graph-run module into studio

community/document-readers/onenote-document-reader/pom.xml, community/document-readers/onenote-document-reader/src/main/java/com/alibaba/cloud/api/reader/onenote/OneNoteDocumentReader.java, community/document-readers/onenote-document-reader/src/main/java/com/alibaba/cloud/api/reader/onenote/OneNoteResource.java, community/document-readers/onenote-document-reader/src/test/java/com/alibaba/cloud/api/reader/onenote/OneNoteDocumentReaderTest.java, pom.xml
This PR introduces the OneNote Document Reader component, which supports fetching content from OneNote resources of three types: Notebook, Section, and individual Page. The component integrates with the Microsoft Graph API to retrieve relevant metadata and page content for each resource type.
该PR引入了OneNote文档读取组件，支持从三种类型的OneNote资源中获取内容：Notebook（笔记本），Section（分区）和单个Page（页面）。该组件与Microsoft Graph API集成，用于获取每种资源类型的相关元数据和页面内容。
https://github.com/alibaba/spring-ai-alibaba/issues/98
- Implement Spring AI's DocumentReader interface
- 实现 Spring AI 的 DocumentReader 接口
- Convert Notion content to Document format
- 将 Notion 内容转换为 Document 格式
- Handle metadata safely with null checks
- 安全处理元数据，包含空值检查
Integration Tests
- Test both page and database reading
- 测试页面和数据库的读取功能
- Verify metadata extraction
- …
=> Feat: Add Google OneNote Document Reader Support

spring-ai-alibaba-core/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
fix bug in maven dependency. When the spring-ai-alibaba-core package is introduced separately and Dashscopechatmodel is manually initialized, the SPRINGBOOT project fails to start. Because of the autoconfiguration of spring-ai-alibaba-core. Imports declares objects that don't belong to this package. In fact, this declaration has been moved to spring-ai-alibaba-autofigure, and the declaration in the core should be removed.
rm AutoConfiguration.imports in spring-ai-alibaba-core
=> rm AutoConfiguration in core

spring-ai-alibaba-autoconfigure/src/main/java/com/alibaba/cloud/ai/autoconfigure/dashscope/DashScopeAutoConfiguration.java
1. current DashScopeImageModel due to the adoption of the retry. It could not work well. So, remove it and have a discussion with @chickenlj.
=> [HotFix]: remove DashScopeImageModel Observation

community/tool-calls/spring-ai-alibaba-starter-tool-calling-microsofttranslate/src/main/java/com/alibaba/cloud/ai/toolcalling/microsofttranslate/MicroSoftTranslateAutoConfiguration.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatModelTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeMultiModalChatTests.java
Added a new integration test case to verify the functionality of the DashScope Deepseek-r1 model. This test ensures that the model can handle real API calls and validates the response structure including the reasoning content.
- Added `testDeepseekR1Integration()` test method with `@Tag("integration")` and `@EnabledIfEnvironmentVariable`
- Test verifies:
- Basic model response functionality
- Response content structure
- Metadata and usage information
- Reasoning content field existence
- Added environment variable check for API key to skip test when not available
- Model: deepseek-r1
- Temperature: 0.7
- Top P: 0.8
- Top K: 50
- Seed: 1234
1. Set environment variable:
```bash
export DASHSCOPE_API_KEY="your-api-key"
```
2. Run integration test:
```bash
./mvnw test …
```
=> Add Integration Test for DashScope Deepseek-r1 Model And Multi Modal Chat

community/document-parsers/document-parser-multi-modality/src/main/java/com/alibaba/cloud/ai/parser/multi/ImageDashScopeParser.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/ApiUtils.java
From the JMH test results, getProperty usually incurs some overhead.
=> reduce redundant getProperty calls to improve performance

community/memories/spring-ai-alibaba-mysql-memory/src/main/java/com/alibaba/cloud/ai/memory/mysql/MysqlChatMemory.java, community/memories/spring-ai-alibaba-mysql-memory/src/main/java/com/alibaba/cloud/ai/memory/mysql/serializer/MessageDeserializer.java
解决Mysql查询序列化Message的问题，具体解决在selectMessageById方法正常
NONE
增加一个反序列化器，识别Message的类别，是UserMessage、AssistantMessage中的哪类
调用/advisor/mysql示例接口，此时Debug能发现selectMessageById正常返回，以前会在改行序列化失败
List<Message> all = (List)this.objectMapper.readValue(oldMessage, new TypeReference<List<Message>>() {
});
=> feat: mysql序列化

community/memories/spring-ai-alibaba-mysql-memory/pom.xml, community/memories/spring-ai-alibaba-redis-memory/pom.xml
Jedis 包编译时打入了，而且Jedis的版本较低，与程序中的jedis运行时冲突，spring boot 3+ 的Jedis默认版本已经是5+，现打包版本升级为5+ 与 optional 由外部程序指定。
MySQL连接池也改为 optional 由外部指定，因为有项目使用 5.7
<optional>true</optional>
程序引入启动验证
=> update mysql redis optional

community/tool-calls/spring-ai-alibaba-starter-tool-calling-baidusearch/src/main/java/com/alibaba/cloud/ai/toolcalling/baidusearch/BaiduSearchAutoConfiguration.java
ConditionalOnProperty 属性 prefix 写成了了value，导致启动报错
=> tools 百度搜索 自动配置bug 修复 prefix

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatOptions.java
This PR translates the Chinese comments in the `DashScopeChatOptions` class to English. It helps international developers better understand the code, promoting cross - cultural collaboration in the project.
Fixes #667.
I first used online translation tools to translate the comments, and then manually adjusted the translations to fit the code context and ensure technical terms were accurate.
Reviewers can compare the translated comments with the original Chinese ones to check for accuracy. They should also ensure the translated terms are appropriate in the code context.
Some technical terms may have multiple translations. If there are any concerns about the translation accuracy or suitability in the code, please feel free to point them out.
=> feat: translate Chinese comments to English in DashScopeChatOptions class

community/openmanus/src/main/java/com/alibaba/cloud/ai/example/manus/planning/creator/PlanCreator.java, community/openmanus/src/main/java/com/alibaba/cloud/ai/example/manus/planning/model/vo/ExecutionPlan.java
ExecutionPlan打印对象地址改为打印具体字段信息，字符串拼接打印改为占位符打印
override toString方法
打印ExecutionPlan对象
只打印了关键字段：planId、title、steps的大小
=> feat(日志打印调整): ExecutionPlan打印对象地址改为打印具体字段信息，字符串拼接打印改为占位符打印

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/CompiledGraph.java
在 CompiledGraph 构造函数中，对 `processedData.interruptsBefore()` 进行了两次重复校验，导致并未对 `interruptsAfter()` 做任何验证。
- 将第二个循环中对 `interruptsBefore()` 的重复引用，改为对 `interruptsAfter()` 进行校验；
=> fix: validate interruptsAfter in CompiledGraph

spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/NacosMcpRegister.java
fix: AsyncServerImpl为McpAsyncServer子类，构造方法传入的为父类而非子类
改为从实际的AsyncServerImpl中获取字段属性
=> fix AsyncServerImpl为McpAsyncServer子类，构造方法传入的为父类而非子类

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/node/ListOperatorNode.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/node/ListOperatorNodeTest.java
The model, when accepting elements of a list such as numbers, strings, or file objects, may need to filter based on specific conditions or sort the list to pass the data to the next Node for processing, thus requiring a ListOperatorNode.
NONE
A generic class `ListOperatorNode` is defined to generate node objects capable of handling different list elements. For consistency, it is specified that `T` must be a subclass of the `ListOperatorNode.ListElement` interface. Predefined classes `NumberElement`, `StringElement`, and `FileElement` are provided to handle lists containing numeric values (a mix of Integer and Double), strings, and file objects respectively. The `FileElement` corresponds to a JSON-formatted file object. These three classes include predefined methods that can be …
=> feat: add ListOperatorNode to graph module

.github/workflows/build-and-test.yml, .github/workflows/lint-pr-title.yml, community/document-readers/spring-ai-alibaba-starter-document-reader-arxiv/src/test/java/com/alibaba/cloud/ai/reader/arxiv/ArxivClientTest.java, community/document-readers/spring-ai-alibaba-starter-document-reader-arxiv/src/test/java/com/alibaba/cloud/ai/reader/arxiv/ArxivDocumentReaderTest.java
1. Close Arxiv UT in github ci environment link https://github.com/alibaba/spring-ai-alibaba/actions/runs/15508814955/job/43667334290;
2. Close PR Title must match the first commit msg condition.
=> fix(document-readers): close Arxiv UT in github ci environment

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/node/VariableAggregatorNode.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/node/VariableAggregatorNodeTest.java
A variable aggregation node has been added, which mainly aggregates the results of multiple branches into one node, simplifying the construction of workflows.
Obtaining path information from overstate for the construction of variable aggregation information allows users to choose whether to enable grouping configuration and outputs results in String or list type.
Currently, unit tests have been added for validation, and in the future, this node will be used to refactor the existing examples of comment classification.
=> feat(graph): add variableAggregatorNode and unit test

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/node/HttpNode.java
fix httpNode return complete response not just the body
However, at present, the node state flow is completely dependent on the upstream node to output a structure that meets the downstream expectations, such as json, md, string, map, etc. If  can't fully account which downstream nodes the output will be sent to, do we need to think about defining a formatNode?
=> fix(graph): httpNode return complete response

spring-ai-alibaba-graph/spring-ai-alibaba-graph-example/src/main/java/com/alibaba/cloud/ai/example/graph/bigtool/controller/BigToolController.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-example/src/main/java/com/alibaba/cloud/ai/example/graph/mcp/McpAutoConfiguration.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-example/src/main/java/com/alibaba/cloud/ai/example/graph/openmanus/OpenmanusController.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-example/src/main/java/com/alibaba/cloud/ai/example/graph/openmanus/human/OpenmanusHumanController.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-example/src/main/java/com/alibaba/cloud/ai/example/graph/reflection/RelectionAutoconfiguration.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-example/src/main/java/com/alibaba/cloud/ai/example/graph/workflow/WorkflowAutoconfiguration.java
replace graph-example deprecated 'new StateGraph' signatures, like:
before :
new StateGraph("Consumer Service Workflow Demo", stateFactory)
now :
StateGraph stateGraph = new StateGraph("Consumer Service Workflow Demo", () -> {
Map<String, KeyStrategy> strategies = new HashMap<>();
strategies.put("input", new ReplaceStrategy());
strategies.put("classifier_output", new ReplaceStrategy());
strategies.put("solution", new ReplaceStrategy());
return strategies;
})
=> fix(graph): replace deprecated method signatures

spring-ai-alibaba-core/pom.xml
fix org/springframework/web/reactive/function/client/WebClient$Builder Class Not Found.
The issue occurs because `DashScopeApi` has a mandatory dependency on `org.springframework.web.reactive.function.client.WebClient`, but the `spring-webflux` dependency is missing in the `pom.xml`, which leads to an exception being thrown.
For reference, the `pom.xml` in `spring-ai-openai` includes the `spring-webflux` dependency:
https://github.com/spring-projects/spring-ai/blob/main/models/spring-ai-openai/pom.xml
Added the `spring-webflux` dependency to the `spring-ai-openai` package where `DashScopeApi` is located.
Users don't need to add the `spring-webflux` dependency manually.
=> fix(core): add `spring-webflux` dependency

auto-configurations/spring-ai-alibaba-autoconfigure-dashscope/src/test/java/com/alibaba/cloud/ai/autoconfigure/dashscope/DashScopeAutoConfigurationIT.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/api/DashScopeApi.java, spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/embedding/DashScopeEmbeddingModel.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/embedding/DashScopeEmbeddingModelTests.java
- Deprecating public constructors in favor of builder API
- Added unit tests and integration tests.
Added support for dimension fields in the vector model.
Fixes #1011
Verified through integration tests in the `DashScopeAutoConfigurationIT` class.
And it works fine on my app too.
=> feat(core): Added support for dimension fields to the embedding model

spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/controller/InteractiveHtmlController.java
- Maintain code style and unify parameter meanings
1. InteractiveHTMLController. buildInteractiveHTML method parameter changed from ReportId to ThreadId
2. Enhance code logic and add verification to check if report data is empty
- 1.Create a request to generate a deep research report
```shell
curl --location --request POST 'http://localhost:8080/deep-research/chat/stream' \
--header 'Content-Type: application/json' \
--data-raw '{
"thread_id": "user1_session1",
"max_plan_iterations": 1,
"max_step_num": 3,
"auto_accepted_plan": true,
"enable_background_investigation": false,
"query": "分析泡泡玛特爆火原因"
}'
```
- 2.use threadId to request and generate a interactive HTML
```shell
curl --location --request GET 'http://localhost:8080/api/interactive-html/build?threadId=user1_session1'
```
=> feat(deepresearch): changed InteractiveHTMLController.buildInteractiveHTML parameter

auto-configurations/spring-ai-alibaba-autoconfigure-dashscope/pom.xml
Existing dashscope autoconfigure pom / stater cannot support spring-ai observation with 1.0.0 version. This PR add observation dependencies in it.
**Image below shows spring-ai-autoconfigure-model-openai pom with corresponding dependencies.**
None
Just add
=> fix(core): add observability support in dashscope autoconfigure pom

auto-configurations/spring-ai-alibaba-autoconfigure-nacos-mcp-client/src/main/java/com/alibaba/cloud/ai/autoconfigure/mcp/client/NacosMcpTransportBuilderAutoConfiguration.java, auto-configurations/spring-ai-alibaba-autoconfigure-nacos-mcp-client/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/client/builder/WebFluxSseClientTransportBuilder.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/client/transport/LoadbalancedMcpAsyncClient.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-nacos/src/main/java/com/alibaba/cloud/ai/mcp/nacos/client/transport/LoadbalancedMcpSyncClient.java
Decouple the construction logic of WebFluxSseClientTransport in Nacos MCP client to to ensure extensibility
解耦 Nacos mcp client 中 WebFluxSseClientTransport 构建逻辑,预留扩展
=> feat(mcp): decouple the construction logic of WebFluxSseClientTransport in Nacos MCP client

spring-ai-alibaba-bom/pom.xml
https://github.com/alibaba/nacos/issues/13358
settings.xml servers use:
```
<server>
<id>central</id>
<username>${CENTRAL_USERNAME}</username>
<password>${CENTRAL_PASSWORD}</password>
</server>
```
Announcement of the End-of-Life Sunset Date for Maven OSSRH
宣布 Maven OSSRH 的生命周期终止日期 ︎
https://central.sonatype.org/news/20250326_ossrh_sunset/#announcement-of-the-end-of-life-sunset-date-for-ossrh
Maven Central Portal Publish Example：https://central.sonatype.com/artifact/cn.ac.xxw/xxw-rsa
Publish command：`mvn -V clean -U package source:jar javadoc:jar deploy -Prelease -DskipTests`
使用与 https://oss.sonatype.org 相同的账户有效在 https://central.sonatype.com/ 登录，即可一键将域名迁移到新平台。
两者密码相同（如果无法登录，可以在 https://central.sonatype.com/ 平台重置密码）
快照功能需要在 https://central.sonatype.com/ 平台的命名空间下手动开启
```
NOTE: If you have …
```
=> :wrench: use Maven Central Portal

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/observation/GraphObservationLifecycleListener.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/observation/node/DefaultGraphNodeObservationConvention.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/observation/node/GraphNodeObservationContext.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/observation/node/GraphNodeObservationDocumentation.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/observation/node/GraphNodeObservationHandler.java
Implement of graph observation cannot display node input state or output state in langfuse.
This PR dynamically add attributes with proper label of OTel gen_ai standard, enabling correct display with langfuse.
NONE
=> fix(graph): enable langfuse input output observation labels

community/memories/spring-ai-alibaba-starter-memory-redis/pom.xml
我今天尝试将jmanus从内存memory切换为redis-mem的时候，发现将auto-mem和redis-mem的starter都引入后依然无法正常使用，甚至启动都会报错。
经过排查我发现是因为在memory-redis项目中引入的jedis限定了不传递
而在autoconfigure-memory中加载RedisChatMemoryAutoConfiguration的条件是需要jedis的
所以这就需要在使用的项目中手动引入jedis，这个错误不容易发现，且我认为starter应该是开箱即用的。我理解不传递jedis是怕redis和jedis的兼容性问题，但是兼容性问题很容易在启动或使用过程中发现，并且大家在使用前也会思考到这个问题，会分析是否需要排除已有的jedis版本引入适配的jedis版本。
我认为应该让jedis的引用传递，更符合starter的开箱即用思想，无论如何都尊重管理员的决定，辛苦啦。
=> fix(memories): resolve the issue where the starter component that introduces memory and Redis still cannot use Redis as memory

community/vector-stores/spring-ai-alibaba-starter-opensearch-store/src/main/java/com/alibaba/cloud/ai/vectorstore/opensearch/OpenSearchVectorStore.java
`
原代码会导致无限递归
public OpenSearchVectorStore build() { 
return OpenSearchVectorStore.builder(this.openSearchApi, this.embeddingModel).build(); 
}
`
NONE
使用com.alibaba.cloud.ai.vectorstore.opensearch.OpenSearchVectorStore#OpenSearchVectorStore(com.alibaba.cloud.ai.vectorstore.opensearch.OpenSearchVectorStore.Builder)构造函数 代替OpenSearchVectorStore.builder(this.openSearchApi, this.embeddingModel).build();
OpenSearchVectorStore.builder(openSearchApi, dashScopeEmbeddingModel).options(openSearchVectorStoreOptions).build();可以成功创建openSearchVectorStore对象并使用。
=> fix(vector-stores): fixed OpenSearchVectorStore.Builder#build 无限递归问题

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/node/AssignerNode.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/node/AssignerNodeTest.java
add a AssignerNode correspond dify's Variable Assigner, ability to assign values to [conversation variables] in the graph, which we stored at OverAllState.
=> feat(graph): add AssignerNode

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatModel.java
根据百炼平台上下文缓存相关文档，会对输入内容进行前缀匹配，匹配到的可以减少token消耗
典型场景中第五点，video放于text之前，多次提问时有概率命中cache
- refer：https://help.aliyun.com/zh/model-studio/context-cache?spm=a2c4g.11186623.help-menu-2400256.d_0_1_7.fae66ff2TF0es4#9770a010abkbq
NONE
- 调整了视频、音频和图像消息的处理顺序
请帮忙检查下，content顺序是否对其他功能有影响
我目前仅发现ChatCompletionMessage 的 content 方法，当 rawContent 为 List 时，会仅取第一条，但其仅对Map类型进行了处理，而此处修改是 MediaContent 类型
=> perf(core): adjust media content sort

spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/streaming/StreamingChatGenerator.java, spring-ai-alibaba-graph/spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/streaming/StreamingOutput.java
- StreamingOutput增强，在 StreamingOutput 类中添加 chatResponse 属性，用于存储 ChatResponse 对象
=> feat(graph): StreamingOutput增强，增加 ChatResponse 属性以获取完整响应

spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/planning/PlanningFactory.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/FormInputTool.java
查询任务加载agent时无法查询对应的提示词，报错promptService is null
因为代码里面想通过bean注入PromptService实例到FormInputTool，而真正使用的时候是新建FormInputTool对象，没有托管到spring，我修复了这一问题。
=> fix(jmanus): fix jmanus promptService is null

spring-ai-alibaba-jmanus/ui-vue3/src/base/i18n/en.ts, spring-ai-alibaba-jmanus/ui-vue3/src/base/i18n/zh.ts
丰富了关于completionsPath的描述，同时我发现设置按钮的国际化配置漏了，一并补充了
=> fix(jmanus): modify and add some descriptions

spring-ai-alibaba-studio/spring-ai-alibaba-studio-server/README.md, spring-ai-alibaba-studio/spring-ai-alibaba-studio-server/docker/middleware/run.sh, spring-ai-alibaba-studio/spring-ai-alibaba-studio-server/frontend/.npmrc, spring-ai-alibaba-studio/spring-ai-alibaba-studio-server/frontend/README.zh-CN.md
1. Change https://registry.anpm.alibaba-inc.com/ to https://registry.npmmirror.com  because registry.anpm.alibaba-inc.com appears to be an internal network address and is inaccessible.
2. Modify chown -R 1000:0 to chmod -R 777， because I found that even if I change it to chown -R 1000:1000 (the docker-compose file specifies 1000:1000), Elasticsearch still fails to start.
NONE
=> fix(studio): fix frontend build error

spring-ai-alibaba-jmanus/pom.xml, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/browser/ChromeDriverService.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/browser/SpringBootPlaywrightInitializer.java
#2018 
原理：
this.getClass().getClassLoader() 返回的是Spring Boot的LaunchedClassLoader
这个类加载器知道如何正确访问fat JAR中的嵌套资源
Playwright的资源查找依赖于当前线程的上下文类加载器
用这个规避 loadURI==null后的报错
=> fix(jmanus): fix the bug where Playwright cannot run when using the Spring Boot fat jar

spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/agent/model/enums/AgentEnum.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/planning/PlanningFactory.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/jsxGenerator/ComponentState.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/jsxGenerator/IJsxGeneratorService.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/jsxGenerator/JsxGeneratorOperator.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/jsxGenerator/JsxGeneratorService.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/tool/jsxGenerator/JsxGeneratorTool.java, spring-ai-alibaba-jmanus/src/main/resources/prompts/startup-agents/en/jsx_generator_agent/agent-config.yml, spring-ai-alibaba-jmanus/src/main/resources/prompts/startup-agents/zh/jsx_generator_agent/agent-config.yml, spring-ai-alibaba-jmanus/src/test/java/com/alibaba/cloud/ai/example/manus/tool/jsxGenerator/JsxGeneratorIntegrationTest.java
Added the jsxGenerator tool and jsxGeneratorAgent, enabling the generation of valid and executable Vue SFC components from natural language descriptions. 
Supported operations include: generate_vue, apply_template, save, validate, list_templates, with corresponding tests added.
#1472 
LLM -> JSON -> Vue SFC -> Handlebars
```json
{
"planType": "simple",
"title": "创建计数器按钮JSX Vue组件",
"directResponse": false,
"steps": [
{
"stepRequirement": "[JSX_GENERATOR_AGENT] 创建基础的JSX Vue组件结构",
"terminateColumns": null
},
{
"stepRequirement": "[JSX_GENERATOR_AGENT] 添加响应式计数器数据和点击事件处理函数",
"terminateColumns": null
},
{
"stepRequirement": "[JSX_GENERATOR_AGENT] 实现按钮点击次数超过5次后改变按钮颜色的逻辑",
"terminateColumns": null
}
],
"planId": "planTemplate-1754630962001"
}
```
Preview is not available yet. The generated code …
=> feat(jmanus): added the jsx_generator tool and jsx_generator agent

spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/llm/LlmService.java, spring-ai-alibaba-jmanus/src/test/java/com/alibaba/cloud/ai/example/manus/llm/DynamicHeaderPreservationTest.java
…ritten
The header of the jmanus dynamic configuration will not be reset when the prompt is obtained from the client
Close #2074
=> fix(jmanus): avoid accidental overwrite of dynamic model configuration

spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/dialect/DynamicColumnIntegrator.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/model/entity/DynamicModelEntity.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/dynamic/model/service/ModelServiceImpl.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/llm/LlmService.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/example/manus/recorder/entity/PlanExecutionRecordEntity.java, spring-ai-alibaba-jmanus/src/main/resources/META-INF/services/org.hibernate.integrator.spi.Integrator
优化pg数据库不兼容问题，目前所有功能在h2、mysql、pg数据库上运转良好
同时也为更多数据库兼容做铺垫
解决不同数据库的方言问题，优化字段的类型问题
=> fix(jmanus): optimize the incompatibility issues of postgres database

spring-ai-alibaba-spring-boot-starters/spring-ai-alibaba-starter-mcp-registry/pom.xml
fix(mcp): fix #2148 使用 spring-ai-starter-mcp-client 替换 spring-ai-starter-mcp-client-webflux
Signed-off-by: traburiss <tingchuan.li@vipshop.com>
不替换会导致使用 pring-ai-starter-mcp-server-webmvc 时产生 404 问题
Fixes #2148
=> fix(mcp): fix #2148 使用 spring-ai-starter-mcp-client 替换 spring-ai-starter-mcp-client-webflux

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/image/DashScopeImageModel.java
The bailian image generation result retrieval is currently asynchronous. The intended design is to achieve polling via retryTemplate retry mechanism.
The injected retryTemplate bean (org.springframework.ai.retry.RetryUtils#DEFAULT_RETRY_TEMPLATE) only retries on org.springframework.ai.retry.TransientAiException
In the current implementation, thrown RuntimeException is not properly handled
This prevents the polling functionality from working as designed
Changing the thrown exception type to TransientAiException has been verified to deliver the expected polling behavior during testing.
百炼生图结果获取是异步轮询的， retryTemplate只能对TransientAiException进行重试处理， 目前的实现只能获取一次生图结果， 并不会进行重试， 将抛错修改TransientAiException， 经验证符合预期
=> fix(core): image gen retry

community/vector-stores/spring-ai-alibaba-starter-tair-store/pom.xml, community/vector-stores/spring-ai-alibaba-starter-tair-store/src/main/java/com/alibaba/cloud/ai/vectorstore/tair/TairVectorStore.java, community/vector-stores/spring-ai-alibaba-starter-tair-store/src/test/java/com/alibaba/cloud/ai/vectorstore/tair/TairVectorStoreTest.java
`TairVectorStore.createObservationContextBuilder()` method was returning `null`, causing `NullPointerException` during vector store operations.
Implemented the method to return a properly configured `VectorStoreObservationContext.Builder` with Tair-specific context information.
- Fixed `createObservationContextBuilder` method implementation
- Added comprehensive unit tests
- Added necessary test dependencies
- ✅ Added unit tests covering default and custom configurations
- ✅ Verified method no longer returns `null`
- ✅ All tests pass
Fixes #2162
=> fix(vector-stores): avoid NPE by returning non-null observation context builder in TairVectorStore (fixes #2162)

spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/OverAllState.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/serializer/plain_text/jackson/JacksonStateSerializer.java, spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/agent/ParallelAgentIntegrationTest.java, spring-ai-alibaba-graph-core/src/test/java/com/alibaba/cloud/ai/graph/agent/SequentialAgentTest.java
add custom deserializer for ToolResponseMessage and improve data handling in OverAllState
fix:
ReactAgentHookTest.testReactAgentWithPostLlmHook:197 » Completion java.util.concurrent.ExecutionException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.springframework.ai.chat.messages.ToolResponseMessage` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1042] (through reference chain: com.alibaba.cloud.ai.graph.OverAllState["data"]->java.util.HashMap["messages"]->java.util.ArrayList[2])
=> feat(graph): add custom deserializer for ToolResponseMessage 

spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/service/business/BusinessKnowledgeRecallService.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/service/semantic/SemanticModelRecallService.java
测试时报数据转换异常
Caused by: org.springframework.dao.InvalidDataAccessApiUsageException: PreparedStatementCallback; SQL [SELECT
business_term,
description,
synonyms,
is_recall,
data_set_id
FROM business_knowledge WHERE data_set_id = ? AND is_recall = 1
]; Feature not supported: "converting to class boolean" [50100-232]
at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:106) ~[spring-jdbc-6.2.6.jar:6.2.6]
NONE
- 将数据库查询结果转换类型从 boolean 改为 Boolean
=> fix(nl2sql): 修复数据转换异常

spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/config/Nl2sqlConfiguration.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/node/SqlExecuteNode.java
当 agentId 为空时，前序节点都没问题，但是SqlExecuteNode 会抛异常，导致流程卡在最后一步
- 在 SqlExecuteNode 构造函数中添加 DbConfig 参数
- 当无法找到智能体 ID 时，返回默认数据源配置
- 更新 Nl2sqlConfiguration 以传递 dbConfig 到 SqlExecuteNode
=> refactor(nl2sql): 优化 SqlExecuteNode 以支持默认数据源配置

spring-ai-alibaba-core/src/main/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeChatModel.java
DashScopeChatModel 实例化时，toolExecutionEligibilityPredicate参数判空bug
无
移除toolExecutionEligibilityPredicate判空，在this.toolExecutionEligibilityPredicate赋值时对空值给默认值
=> fix(core): fix DashScopeChatModel 实例化时参数判空bug

pom.xml, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/chat/DashScopeMultiModalChatTests.java, spring-ai-alibaba-core/src/test/java/com/alibaba/cloud/ai/dashscope/image/observation/DashScopeImageModelObservationITests.java, spring-ai-alibaba-deepresearch/pom.xml, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/controller/ChatController.java, spring-ai-alibaba-graph-core/pom.xml, spring-ai-alibaba-jmanus/pom.xml, spring-ai-alibaba-nl2sql/pom.xml, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/pom.xml, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-common/pom.xml, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-management/pom.xml
feat(core): upgrade spring-ai to 1.0.1, spring-boot to 3.4.8 and fix test hang in mac with docker
=> feat(core): upgrade spring-ai to 1.0.1, spring-boot to 3.4.8

spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-management/src/main/java/com/alibaba/cloud/ai/entity/BusinessKnowledge.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-management/src/main/java/com/alibaba/cloud/ai/entity/SemanticModel.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-management/src/main/java/com/alibaba/cloud/ai/mapper/BusinessKnowledgeMapper.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-management/src/main/java/com/alibaba/cloud/ai/mapper/SemanticModelMapper.java
修正nl2sql模块中实体类字段映射与数据库schema不一致的问题。
当前BusinessKnowledge和SemanticModel实体类的@TableField注解与实际数据库表字段名不匹配，导致保存语义模型实体时出错。
为保持向前兼容，以及确保现有sql查询正常运行，我选择修改映射字段。
Fixes #2171 
调整实体类的@TableField注解，使其与数据库schema完全匹配
确认实体类@TableField注解与数据库schema.sql中的字段名一致
这是一个字段映射的修复，没有改变业务逻辑，只是确保ORM映射的正确性。
修改后的字段映射与现有的硬编码SQL查询保持一致。
=> fix(nl2sql): 修正实体类字段映射与数据库schema不一致

spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-common/src/main/java/com/alibaba/cloud/ai/mcp/nacos/service/NacosMcpOperationService.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-router/src/main/java/com/alibaba/cloud/ai/mcp/gateway/core/jsontemplate/RequestTemplateInfo.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-router/src/main/java/com/alibaba/cloud/ai/mcp/gateway/core/jsontemplate/RequestTemplateParser.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-router/src/main/java/com/alibaba/cloud/ai/mcp/gateway/nacos/callback/NacosMcpGatewayToolCallback.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-router/src/main/java/com/alibaba/cloud/ai/mcp/gateway/nacos/provider/NacosMcpAsyncGatewayToolsProvider.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-router/src/main/java/com/alibaba/cloud/ai/mcp/gateway/nacos/provider/NacosMcpSyncGatewayToolsProvider.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-router/src/main/java/com/alibaba/cloud/ai/mcp/gateway/nacos/watcher/NacosMcpGatewayToolsWatcher.java
Nacos MCP Gateway 的当前实现进行 HTTP 接口转 MCP 服务时，是基于 Higress的 MCP 模版规则进行的，但是 Nacos 采用的模板规则和Higress的模版规则有略微不同，导致部分 Nacos 模版无法被正确解析， HTTP 服务无法正确转化 MCP 服务。
因此本PR主要对这部分内容进行了修正，以及进行了相关的功能增强。
主要包括以下内容：
-  参数支持通过argsPosition指定传参位置
-  支持在模版中引用 Nacos 配置内容
-  修复了模版解析中存在的一些问题
Nacos MCP 模版规则参考官方文档: [MCP 模版配置手册](https://nacos.io/docs/latest/manual/user/ai/mcp-template/?spm=5238cd80.521abf88.0.0.5277b2c3bKbWJ2)
=> fix(mcp): 修复 Nacos MCP Gateway 解析 Nacos MCP 模版的若干问题

spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-router/pom.xml, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-router/src/main/java/com/alibaba/cloud/ai/mcp/gateway/core/jsontemplate/ResponseTemplateParser.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-router/src/test/java/com/alibaba/cloud/ai/mcp/gateway/core/jsontemplate/ResponseTemplateParserTest.java
Using Handlebars.java, we support multi-level data extraction using MCP. Simple extraction still uses the original strategy.
#2389 
Using Handlebars.java, we support multi-level data extraction using MCP. Simple extraction still uses the original strategy.
=> feat(mcp): support multi-level data extraction

spring-ai-alibaba-studio/spring-ai-alibaba-studio-server/spring-ai-alibaba-studio-server-admin/pom.xml, spring-ai-alibaba-studio/spring-ai-alibaba-studio-server/spring-ai-alibaba-studio-server-admin/src/main/java/com/alibaba/cloud/ai/studio/admin/SaaStudioApplication.java, spring-ai-alibaba-studio/spring-ai-alibaba-studio-server/spring-ai-alibaba-studio-server-admin/src/main/java/com/alibaba/cloud/ai/studio/admin/generator/GeneratorApplication.java, spring-ai-alibaba-studio/spring-ai-alibaba-studio-server/spring-ai-alibaba-studio-server-admin/src/main/java/com/alibaba/cloud/ai/studio/admin/generator/controller/GeneratorController.java, spring-ai-alibaba-studio/spring-ai-alibaba-studio-server/spring-ai-alibaba-studio-server-admin/src/main/java/com/alibaba/cloud/ai/studio/admin/generator/service/generator/workflow/sections/KnowledgeRetrievalNodeSection.java
Based on user feedback, a new startup class has been added that only provides low-code generation. This startup class solely activates the DSL-to-code conversion feature of the Studio and does not support other Studio functionalities. There is no need to start middleware such as rocketMQ. Both startup classes have been tested.
This solution is only a temporary measure. It can be modified later to activate specific functions based on the user's configuration needs.
=> feat(studio): support dsl2saa only Application

pom.xml, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-common/src/main/java/com/alibaba/cloud/ai/mcp/nacos/service/NacosMcpOperationService.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-registry/src/main/java/com/alibaba/cloud/ai/mcp/discovery/client/transport/LoadbalancedMcpAsyncClient.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-registry/src/main/java/com/alibaba/cloud/ai/mcp/discovery/client/transport/LoadbalancedMcpSyncClient.java, spring-ai-alibaba-mcp/spring-ai-alibaba-mcp-registry/src/main/java/com/alibaba/cloud/ai/mcp/discovery/client/utils/NacosMcpClientUtils.java
目前发现 mcp 时， protocol字段是写死的http，导致无法正确发现 https 的 mcp server, 修复这个问题
fix #2407
=> fix(mcp): 修复发现注册到 nacos 上的 mcp server 时， 无法正确发现 https 协议的 mcp server 的问题

pom.xml, spring-ai-alibaba-agent-nacos/pom.xml, spring-ai-alibaba-agent-nacos/src/main/java/com/alibaba/cloud/ai/agent/nacos/NacosAgentBuilderFactory.java, spring-ai-alibaba-agent-nacos/src/main/java/com/alibaba/cloud/ai/agent/nacos/NacosAgentInjector.java, spring-ai-alibaba-agent-nacos/src/main/java/com/alibaba/cloud/ai/agent/nacos/NacosMcpToolsInjector.java, spring-ai-alibaba-agent-nacos/src/main/java/com/alibaba/cloud/ai/agent/nacos/NacosModelInjector.java, spring-ai-alibaba-agent-nacos/src/main/java/com/alibaba/cloud/ai/agent/nacos/NacosOptions.java, spring-ai-alibaba-agent-nacos/src/main/java/com/alibaba/cloud/ai/agent/nacos/NacosPartenerAgentsInjector.java, spring-ai-alibaba-agent-nacos/src/main/java/com/alibaba/cloud/ai/agent/nacos/NacosPromptInjector.java, spring-ai-alibaba-agent-nacos/src/main/java/com/alibaba/cloud/ai/agent/nacos/NacosReactAgentBuilder.java, spring-ai-alibaba-agent-nacos/src/main/java/com/alibaba/cloud/ai/agent/nacos/ObservationConfigration.java, spring-ai-alibaba-agent-nacos/src/main/java/com/alibaba/cloud/ai/agent/nacos/tools/NacosMcpGatewayToolCallback.java, spring-ai-alibaba-agent-nacos/src/main/java/com/alibaba/cloud/ai/agent/nacos/tools/NacosMcpGatewayToolsInitializer.java, spring-ai-alibaba-agent-nacos/src/main/java/com/alibaba/cloud/ai/agent/nacos/vo/AgentVO.java, spring-ai-alibaba-agent-nacos/src/main/java/com/alibaba/cloud/ai/agent/nacos/vo/McpServersVO.java, spring-ai-alibaba-agent-nacos/src/main/java/com/alibaba/cloud/ai/agent/nacos/vo/MemoryVO.java, spring-ai-alibaba-agent-nacos/src/main/java/com/alibaba/cloud/ai/agent/nacos/vo/ModelVO.java, spring-ai-alibaba-agent-nacos/src/main/java/com/alibaba/cloud/ai/agent/nacos/vo/PartnerAgentsVO.java, spring-ai-alibaba-agent-nacos/src/main/java/com/alibaba/cloud/ai/agent/nacos/vo/PromptVO.java, spring-ai-alibaba-bom/pom.xml, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/agent/Builder.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/agent/DefaultBuilder.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/agent/ReactAgent.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/agent/factory/AgentBuilderFactory.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/agent/factory/DefaultAgentBuilderFactory.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/node/LlmNode.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/node/ToolNode.java
=> nacos proxy reactagent

spring-ai-alibaba-deepresearch/DeepResearch.http, spring-ai-alibaba-deepresearch/README-zh.md, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/config/DeepResearchConfiguration.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/controller/ChatController.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/controller/graph/GraphProcess.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/model/req/FeedbackRequest.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/HumanFeedbackNode.java, spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/PlannerNode.java, spring-ai-alibaba-deepresearch/src/test/resources/application-python_basis.yaml, spring-ai-alibaba-deepresearch/src/test/resources/application-python_network.yaml, spring-ai-alibaba-deepresearch/ui-vue3/src/views/chat/index.vue, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/node/HumanFeedbackNode.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/main/java/com/alibaba/cloud/ai/service/Nl2SqlService.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-chat/src/test/java/com/alibaba/cloud/ai/node/HumanFeedbackNodeTest.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-management/src/main/java/com/alibaba/cloud/ai/controller/Nl2sqlForGraphController.java, spring-ai-alibaba-nl2sql/spring-ai-alibaba-nl2sql-web-ui/src/views/AgentRun.vue
chore(deepsearch): fix typos
feed_back 是一个词 feedback
=> chore(deepresearch): fix typos

spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/manus/OpenManusSpringBootApplication.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/manus/playwright/ManusDriverJar.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/manus/tool/browser/ChromeDriverService.java, spring-ai-alibaba-jmanus/src/main/java/com/alibaba/cloud/ai/manus/tool/browser/SpringBootPlaywrightInitializer.java
优化Jmanus浏览器下载，默认只下载chromium，这样第一次用的时候速度更快，并且可以通过环境变量指定浏览器
Fixes #2170
最好的方式是PlayWright底层支持指定单独下载某个浏览器，但是它目前不支持，只支持自定义DriverJar的实现类，所以我自定义了一个ManusDriverJar，在installBrowsers方法中会读取环境变量playwright.browser的值，然后添加到install命令后，这样就只会下载指定的浏览器了。
另外在PlayWright的Driver类中，只支持通过环境变量来指定实现类，所以我也只能通过环境变量的方式来设置实现类ManusDriverJar：
playwright-init启动的方式，正常启动第一次调用，jar包启动第一次调用都测了，都只会下载chromium浏览器，好像没有没有更好的测试方法
是否有更好的优化方式？
=> fix(jmanus): 优化Jmanus浏览器下载，默认只下载chromium（#2170）

spring-ai-alibaba-deepresearch/src/main/java/com/alibaba/cloud/ai/example/deepresearch/node/BackgroundInvestigationNode.java
- 原实现会不断覆盖前一个查询的查询结果
- 修改结果的保存方式，确保所有查询结果都被正确保存
- 修复背景调查节点的结果列表大小比较逻辑
- 将不等修正为相等
- 确保结果列表与查询列表的大小一致，避免潜在的索引越界问题
NONE
=> fix(deepresearch): 修复背景调查节点的查询结果

spring-ai-alibaba-graph-core/pom.xml, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/GraphRunnerContext.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/OverAllStateBuilder.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/executor/MainGraphExecutor.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/executor/NodeExecutor.java, spring-ai-alibaba-graph-core/src/main/java/com/alibaba/cloud/ai/graph/utils/SerializationUtils.java
1. deepcopy `input data` used to initialize state.
2. fix state update after node execution.
=> fix(graph): duplicated messages in state
